### ISSUE TITLE
Add a field to database.json for main entry point of module

### ISSUE THREAD

**Issue by sholladay** [denoland/dotland#110]
I want people to be able to `import pogo from 'https://deno.land/x/pogo'`, but right now that doesn't work because the registry doesn't know which file to point to.

It would be great if I could specify the main entry point in database.json.

I created [module-url](https://github.com/sholladay/module-url) to make this a bit easier. It is a utility that takes an object as input, in nearly the same format as is used in database.json, and it returns a URL string of where to fetch the module from.

**Comment by ry** [comment]
I’m open to it.

**Comment by crowlKats** [comment]
Since we dont have database.json, i am closing
