### ISSUE TITLE
repl.it added support for deno

### ISSUE THREAD

**Issue by rafaelcastrocouto** [denoland/dotland#1104]
repl.it now supports deno in their website

we could add a "try it online" link for it, I'm just not sure where it should go 😁

maybe in the "get started" or in the manual?

https://repl.it/

https://github.com/replit/polygott/issues/62

**Comment by lucacasonato** [comment]
@ry WDYT? Might be cool

**Comment by amasad** [comment]
FYI here is a direct link: https://repl.it/languages/deno

We're also actively making it better:
- GUI for packager search and managing dependencies (see [upm](https://blog.repl.it/upm))
- Better code intellisense/linting: right now we're using Typescript LSP which as you know doesn't work well with Deno

Let us know if you have any feedback (founder here).

**Comment by rafaelcastrocouto** [comment]
I just realized it could be used to add demo snippets to the manual.

**Comment by Soremwar** [comment]
@rafaelcastrocouto Is there anyway I can open an issue regarding problems/suggestion to the repo implementation?

**Comment by 00ff0000red** [comment]
> @amasad Is there any place I can open an issue regarding problems/suggestion to the repl implementation?

As it seemed like no one had ever responded to you, I'd recommend https://github.com/replit/polygott/issues or just https://github.com/replit.

**Comment by amasad** [comment]
The polygott issue tracker is not a bad place for that. We also have https://repl.it/bugs too

**Comment by crowlKats** [comment]
replit's Deno version is extremely outdated (over a year and a half old), so seems not maintained properly anymore; linking to it makes little sense currently, so closing
