### ISSUE TITLE
Errors when importing TypeScript files using `deno.land/x` tool

### ISSUE THREAD

**Issue by moshest** [denoland/dotland#1136]
Please check out this issue: https://github.com/neuledge/computed-types/issues/34

The use case is that we want to allow user to import native TypeScript from the github repo and use them in Deno. The problem is that Deno requires file extensions when importing files while TypeScript [literally breaks](https://github.com/neuledge/computed-types/issues/34) when trying to import files with extensions.

This making it very hard to maintain TypeScript project that support both Deno and TypeScript.

I tried to use Pika CDN and jspm.io, both failed to load and generated [an error](https://github.com/neuledge/computed-types/issues/34).

@SirJosh3917 came with very elegant idea and created a worker that can server TypeScript files from any source for Deno. We tried it on my library and it works perfect!

You can check the source code here: https://github.com/SirJosh3917/denoporter

Any chance to integrate that functionality in `deno.land/x` worker or at least dedicate a subdomain for this service so URL will looks nicer?

Current URL is https://denoporter.sirjosh.workers.dev/v1/deno.land/x/computed_types/src/index.ts

**Comment by crowlKats** [comment]
This is out of scope for the registry, and a third party solution as suggested would make more sense to be used.
