### ISSUE TITLE
Empty modules on /x/

### ISSUE THREAD

**Issue by danbulant** [denoland/dotland#1293]
Hey.

Can I ask why are there empty modules (with just basic README but no actual code) in x? Why are there in x when they're unusable? I thought x was only for (at least basically) working modules, not for nearly empty READMEs

**Comment by ebebbington** [comment]
More on this, i'm curious why modules are being allowed in when they either have no tests (or tests failing), or are one-liners, essentially (similar to OP's comment) lowering the quality of /x/, then people try use modules that don't work

**Comment by crowlKats** [comment]
@ebebbington agreed. this goes back to #548

**Comment by lucacasonato** [comment]
`/x/` is meant to be a simple hosting service for all modules - it is not a curated list and it is not meant to be. The PR workflow to get modules onto `/x` makes it look like there is a review before modules are published. This is not the case. The PR workflow is just a relic from when `/x` only had a few dozen modules. A new publishing process that does not involve human 'review' is currently in the works.

There are also plans for quality metrics (is formatted, has no lint errors, has tests, good coverage) and popularity metrics to make choosing modules easier. We are also working on better discoverability. I hope that introducing metrics and better search / ranking will discourage people to build and download modules that are just one liners, don't work, aren't updated, or are just generally low quality.

I can't give you an ETA for any of this, but there is progress being made.

**Comment by danbulant** [comment]
One liners aren't actually that bad. I was talking about modules like [this](https://deno.land/x/blox) or [this](https://deno.land/x/roblox) that are just default GitHub READMEs, so they can't even be included in actual scripts at all.

> A new publishing process that does not involve human 'review' is currently in the works.

It could be just a simple GH action checking if there are tests and if they run correctly and if it has code at all (at least basic `mod.ts`), just like you said.

Maybe a system of upvotes/kudos/likes/downloads could be used to sort the modules (instead of the default alphabetic sort)? There are some libraries "better" (or more used/polished etc) that get put down by nearly empty modules, just because they have emoji or number at start.

**Comment by eliassjogreen** [comment]
> There are also plans for quality metrics (is formatted, has no lint errors, has tests, good coverage) and popularity metrics to make choosing modules easier. We are also working on better discoverability. I hope that introducing metrics and better search / ranking will discourage people to build and download modules that are just one liners, don't work, aren't updated, or are just generally low quality.

Me and @qu4k have developed [sauron](https://github.com/denosaurs/sauron) a tool that outputs different quality metrics for deno modules developed for use in registries.

**Comment by jsejcksn** [comment]
- What about name reservations with with code, but no maintenance or updates?
- What about no updates in _n_ duration?
- What about other situations?
- etc.

For reference: How npm handles module name disputes: https://docs.npmjs.com/using-npm/disputes.html

I think it is good to formalize Deno's official position on this, because https://deno.land/x is viewed as the "official" third-party registry.

**Comment by timreichen** [comment]
I would also put module naming on the list. It is all over the place and feels really messy. Some names include prefixes like `deno` (example: `deno_csv`), some don't, some are upper some lowercase. Some are just copied npm modules (like [lodash](https://deno.land/x/lodash@4.17.19)), some are ports to deno, some with features already existing in `std`.

First I thought, /x contain modules that extend the functionality of `std` and is maintained by 3rd party and could potentially be included in `std` if it is a widely used spec. But it seems to be just another module registry as described above.

If it is supposed to be that, I think we definitely should have a look at
- scoped urls (something like described [here](https://github.com/denoland/deno_registry2/issues/67))
- categorization for modules
- style guide (something like [this](https://deno.land/manual/contributing/style_guide) for /x modules)
