### ISSUE TITLE
Add link unfurling for deno.land urls

### ISSUE THREAD

**Issue by jeroenptrs** [denoland/dotland#1456]
This is especially noticeable for deno.land/x modules that are linked through slack/discord. There's no preview (link unfurling) happening as far as I can tell with any links coming from deno.land, but unfurler does give results for opengraph and twitter:
https://unfurler.com/?url=https:%2F%2Fdeno.land%2Fmanual

**Comment by smkamranqadri** [comment]
I would like to take this?

**Comment by lucacasonato** [comment]
@smkamranqadri Thanks for the offer, but we had this previously, but removed it again. Before adding this again we need to decide exactly what we want.

**Comment by smkamranqadri** [comment]
Noted with thanks, let me know if I can be any help.

**Comment by crowlKats** [comment]
This has been addressed.
