### ISSUE TITLE
Order version tags by semantic version number

### ISSUE THREAD

**Issue by srackham** [denoland/dotland#1513]
Order version tags in the deno.land third party modules drop-down versions list by semantic version number (ignoring the 'v' prefix).

Currently (1) if a Github project containing a mix of 'v' and non 'v' prefixed version numbers is imported to deno.land/x/ then the 'v' tags appear at the top of the list irrespective of their semantic version number or chronological ordering (I suspect this is because this is how Github orders them).

New tags created after the initial publication are inserted at the top of the list see: https://deno.land/x/rimu

**Background**: Early on in the project (pre-Deno) the tag naming convention dropped the 'v' character tag prefix. The legacy 'v' tags have since been deleted on Github (this occurred after the project was published to deno.land/x/rimu).

Aside from orphaned 'v' tags this would not have been an issue if the deno.land drop-down version number list was reverse-ordered by semantic version number.

Note (1): The rimu module was initially published to deno.land prior to the Github webhooks publication functionality, it may be that only projects imported before webhooks are affected?

**Comment by crowlKats** [comment]
Versions will always be listed in release order, we wont add special ordering for semver
