### ISSUE TITLE
Not found pages haven't response status code 404

### ISSUE THREAD

**Issue by eusonlito** [denoland/dotland#1592]
All not existing pages should return a `404` status code on response to allow to search engines and any request to `deno.land` to manage this errors as `404` errors and not as `200` success. For example, obsolete modules:

```
Download https://deno.land/x/postcss@8.1.2/lib/postcss.js
error: Uncaught (in promise) TypeError: An unsupported media type was attempted to be imported as a module.
  Specifier: https://deno.land/deno/postcss-deno-import/deno/mod.js
  MediaType: Unknown
```

`statusCode={404}` was removed on PR Custom 404 page 🦕 https://github.com/denoland/deno_website2/pull/1570

**Comment by Duelsik** [comment]
#1654

**Comment by Duelsik** [comment]
Created PR for that, fingers crossed 😄

**Comment by crowlKats** [comment]
Since we switched to fresh, we provide 404 status with the caveat of https://github.com/denoland/dotland/issues/2258
