### ISSUE TITLE
Main Menu disappears on Desktop

### ISSUE THREAD

**Issue by Maxvien** [denoland/dotland#1603]
![image](https://user-images.githubusercontent.com/1142799/99042853-0c956d00-25c0-11eb-96c4-eaf60f0fc359.png)

**Comment by Codercise** [comment]
Hey @Maxvien, can you still see this bug? Looks like it's been resolved.

**Comment by Maxvien** [comment]
@Codercise The bug is still there. It only happens on **Edge**.

![image](https://user-images.githubusercontent.com/1142799/131935644-3427d982-0e68-428f-bac1-efe8118a8519.png)

**Comment by kt3k** [comment]
It doesn't reproduce with the latest Edge (94.0.992.31) on my machine (macOS).

Is your Edge at the latest version? What happens if you disable the browser extensions?

**Comment by Maxvien** [comment]
@kt3k I have checked it again. And this [extension](https://chrome.google.com/webstore/detail/laban-dictionary-by-laban/kdoofkpcjhkbhedgkdbagobockcmeoeb?hl=vi) causes trouble.

**Comment by nickhayden-petstock** [comment]
Thanks for checking again @Maxvien. Looks like we can close this one.

Do you know what in particular the extension was doing to hide the menu? It doesn't seem like something we should worry about but would be good to go for the future.

**Comment by Codercise** [comment]
Thanks for checking again @Maxvien. Looks like we can close this one.

Do you know what in particular the extension was doing to hide the menu? It doesn't seem like something we should worry about but would be good to go for the future.

**Comment by Maxvien** [comment]
@Codercise The bug occurs only on websites using Tailwind. Maybe, the extension has duplicated CSS rulesets with Tailwind. I think we should close this issue.
