### ISSUE TITLE
re-add metadata

### ISSUE THREAD

**Issue by 4ldas** [denoland/dotland#1605]
Re-add metadata to the website as it makes the website seem less suspicious and tells about the website before going inside it from 3rd party sites and such.

**Comment by nickhayden-petstock** [comment]
Hi @4ldas, is there any particular metadata that you're wanting to add? I just ran the site through: https://socialsharepreview.com/?url=https://deno.land and saw that outside of og:image that everything looked fine and what we would expect.

**Comment by Codercise** [comment]
Hi @4ldas, is there any particular metadata that you're wanting to add? I just ran the site through: https://socialsharepreview.com/?url=https://deno.land and saw that outside of og:image that everything looked fine and what we would expect.

**Comment by SamipPoudel58** [comment]
@Codercise Is there a reason for not adding og:image? Does it improve Page-load time?

**Comment by crowlKats** [comment]
Closing in favour of #1456 as no further metadata has been specified
