### ISSUE TITLE
deno.lad/x edit optional directory in my repo

### ISSUE THREAD

**Issue by aricart** [denoland/dotland#1671]
Hi All,

I am having trouble with my deno.land/x/nats project.
Ever since the change to website 2, references to deno.land/x/nats have been broken. The reason being is that the project's main module is indeed the optional directory of the repo, but the module has other dependencies on other modules on the same repo which are siblings to the optional directory, ie:

my main module is `deno.land/x/nats@master/mod.ts`, but that depends on modules referenced as `../nats-base-client/...`. When the URL rewrites, it creates references that are not accessible, thus the module doesn't work (it did way back in the way back upto version v0.1.1-19).

Can you folks remove the `optional` directory from my project, this should make my project work again using the deno.land/x. Previously it may have been possible to self-fix, but not anymore.

Thanks!

**Comment by aricart** [comment]
https://github.com/nats-io/nats.deno#109

**Comment by lucacasonato** [comment]
Just update your webhook. It has the sub directory specified in the query parameters.

**Comment by aricart** [comment]
Thank you @lucacasonato  - I will do a release to trigger it.

**Comment by lino-levan** [comment]
Was this resolved? I believe this issue should be closed.
