### ISSUE TITLE
Improve description of subdirectoy for denoland/x

### ISSUE THREAD

**Issue by NaridaL** [denoland/dotland#1712]
Followup to https://github.com/denoland/deno_registry2/issues/213

I'd submit a PR myself, but I'm unclear on what exactly the usage scenario for the subdirectory is, if separately versioned modules aren't supported.

**Comment by wperron** [comment]
cc @lucacasonato

**Comment by lucacasonato** [comment]
It is meant to be used for modules that have both a Node and a Deno version (for example `//deno` directory and `//node` directory. They would be versioned identically. Seperately versioned modules are supported, they are not documented though (see `version_prefix` query parameter in https://github.com/denoland/deno_registry2/blob/main/API.md).

**Comment by crowlKats** [comment]
Closing as stale
