### ISSUE TITLE
Add countdown clock for next releases 

### ISSUE THREAD

**Issue by ry** [denoland/dotland#1730]
It would be great to have something like https://www.chromestatus.com/features/schedule

https://deno.land/manual@main/contributing/release_schedule is rather buried

**Comment by DimaRomaniuk** [comment]
![image](https://user-images.githubusercontent.com/39365936/127783432-77a44854-7f3d-4a7e-9310-3f7b712e6e65.png)
@ry of course it's a draft, but could you share your thoughts ?

**Comment by ry** [comment]
I changed my mind on this - it's too much work for us to maintain "next release" dates 
https://github.com/denoland/dotland/pull/2127#discussion_r862831285
