### ISSUE TITLE
Add a link to GitHub release notes on /x/:module

### ISSUE THREAD

**Issue by satyarohith** [denoland/dotland#1769]
It would be handy to link to the module's GitHub releases page beside the star count.

![CleanShot 2021-06-08 at 11 07 43@2x](https://user-images.githubusercontent.com/29819102/121129021-f3008f00-c849-11eb-8cff-25197001372d.png)

Note: the link should point to the selected tag.

**Comment by GuiltyDolphin** [comment]
Yep. Would be great if we could pull in information from the changelog here too (maybe the link could point to that if a changelog exists?). And we should make sure that the icon displays something like "Release notes" when hovering over it, for clarity.

**Comment by crowlKats** [comment]
This would have very little usage for the space it would take up, and the same can be achieved with 2 more clicks, so closing
