### ISSUE TITLE
Add link to https://github.com/denoland/deno/wiki#list-of-companies-using-deno

### ISSUE THREAD

**Issue by ry** [denoland/dotland#1776]
not sure where

**Comment by Haydos585** [comment]
Would adding a "Showcase" link to the footer meet the requirements for this ticket or do you think it should be more obvious or higher up?

![image](https://user-images.githubusercontent.com/1107659/122496808-b560ea80-d02f-11eb-950f-c44b6e1b0729.png)

**Comment by kt3k** [comment]
It's more of a marketing item than proper showcase in my view. Maybe below the feature list in the top page?

<img width="977" alt="スクリーンショット 2021-06-21 11 54 36" src="https://user-images.githubusercontent.com/613956/122701138-8c3a9700-d287-11eb-85c8-495aee781fb7.png">
