### ISSUE TITLE
Substituted std version does not change when changing std version drop down

### ISSUE THREAD

**Issue by dsherret** [denoland/dotland#1787]
1. Go to https://deno.land/std@0.99.0/flags
2. Change std version in drop down to anything except 0.99.0

After step 2, the substituted std version will not match the version selected.

**Comment by Hardik500** [comment]
@dsherret 
In my case it was resetting back to `0.103.0` version, i.e. the latest version.

I am happy to work on this issue, if you aren't taking it.
