### ISSUE TITLE
Tab freezes when opening binary files

### ISSUE THREAD

**Issue by archoki** [denoland/dotland#1810]
When opening a binary files, (e.g. `.wasm`), the tab will freezes until the file finish loading. My suggestion is, preventing users from viewing these files or, redirect them to the project repository. The cause of the freezes is unknown but I did see some uncaught promise rejection
![image](https://user-images.githubusercontent.com/87886124/126891490-ba535121-ae26-4393-84a6-fb9405a070c2.png)

Don't know if the image is helpful but hope it is!

**Comment by archoki** [comment]
An idea by **evan#9999** (on Discord) is to convert the `.wasm` to `.wat` files. This maybe achievable but it will still takes time to load. This might be a good idea for small files. For larger files, we can stick to preventing users from opening the "raw" binary or redirect users to the project repo

**Comment by crowlKats** [comment]
This shouldnt be happening anymore. Created https://github.com/denoland/dotland/issues/2278 for WASM rendering in WAT format
