### ISSUE TITLE
Imprint

### ISSUE THREAD

**Issue by Aloso** [denoland/dotland#1892]
Who is in charge of the Deno company? Who owns the company? In which country is it and what is its legal form? Who is responsible for the content on the website? How can I contact them? Where are the servers located? What data is collected?

These are some of the questions I would like to see answered on the website. If I share personal information in order to sign up for Deno Deploy or sign a CLA for contributing to Deno, I think it is reasonable to expect some transparency.

Some of this information is actually required by law, at least in Germany where I live.

**Comment by lucacasonato** [comment]
Hey @Aloso. Thanks for the feedback.

The Deno company is a corporation, incorporated in Delaware, US under the name Deno Land Inc. Ryan Dahl is the CEO. You can contact us at deploy@deno.com. Deno Land Inc is responsible for the content of the websites under the deno.land and deno.com domains. Servers are located all across the world, but all company data is stored in mainland USA, and is encrypted at rest.

https://deno.land collects no personally identifiable data at all.

Currently Deno Deploy (https://deno.com/deploy) only stores the following data about each signed up user:

- A unique user ID
- Name (from your GitHub account)
- Username
- GitHub user ID
- Account creation timestamp

We put together a small "About the company" page at https://deno.com/company/ now.

**Comment by Aloso** [comment]
Thanks, I really appreciate it!
