### ISSUE TITLE
Link over-escaped

### ISSUE THREAD

**Issue by regseb** [denoland/dotland#1911]
Hi,

In the _README_ of the Third Party Modules, the links seem to over-escaped. For example for the link :

```
https://img.shields.io/endpoint?label=coverage&url=https%3A%2F%2Fbadge-api.stryker-mutator.io%2Fgithub.com%2Fregseb%2Fcronnor%2Fmaster
```

, the request is :

```
https://img.shields.io/endpoint?label=coverage&url=https%253A%252F%252Fbadge-api.stryker-mutator.io%252Fgithub.com%252Fregseb%252Fcronnor%252Fmaster
```
(cf. badge _coverage_ of [_cronnor_](https://deno.land/x/cronnor@v1.3.0/README.md)).

**Comment by KillyMXI** [comment]
Same issue.
Ironically, when trying to include a badge for `deno.land/x/` itself:
![image](https://user-images.githubusercontent.com/13851064/139485285-659fa8ed-7c79-4533-910a-1e320ae9dd79.png)

**Comment by regseb** [comment]
The problem seems to be fixed (maybe thanks to the pull request https://github.com/denoland/dotland/pull/1897). The badge _coverage_ of [cronnor](https://deno.land/x/cronnor@v1.3.0/README.md) and the _deno.land/x/_ of [peberminta](https://deno.land/x/peberminta@v0.7.0) are displayed correctly.

**Comment by KillyMXI** [comment]
I confirm my badges are displayed correctly.

Funny how it is broken in a different way now. It now preserves single line breaks, unlike all other places where my Readme is displayed.

![image](https://user-images.githubusercontent.com/13851064/156374393-b0ee9c2b-6880-43bb-bd22-3f9fced22bc8.png)

**Comment by regseb** [comment]
> Funny how it is broken in a different way now. It now preserves single line breaks, unlike all other places where my Readme is displayed.

@KillyMXI I open a new issue https://github.com/denoland/dotland/issues/2038 to line break.
