### ISSUE TITLE
Accept hyphens in the name of modules

### ISSUE THREAD

**Issue by yooneskh** [denoland/dotland#1913]
Can we please have hyphens in the name of modules too? currently it is only letters, numbers and underscores and i really don't see why hyphens are not included.

This causes the problem that some modules names are like "abc-abc" in github and everywhere else and they suddenly become "abc_abc" in the deno.lands url.

Also i personally like kebab-case better and really don't see the reason for this restriction.

Thanks in advance.

**Comment by MierenManz** [comment]
This has been requested and rejected multiple times since the registry started.
The reason why it doesn't allow hyphens is so that you do not get duplicated modules like `abc-abc` and `abc_abc` on the registry while they're the same package.
