### ISSUE TITLE
Use "docs" instead of "Manual"

### ISSUE THREAD

**Issue by babakfp** [denoland/dotland#1931]
![Annotation 2021-11-07 081239](https://user-images.githubusercontent.com/44144724/140632547-81ca37c2-fdd5-45e5-be8e-e0477b77f232.png)
It's more familiar and user-friendly to use "docs" instead of "manual".

**Comment by kitsonk** [comment]
More familiar is a relative concept.

**Comment by babakfp** [comment]
It's true, but we can agree that the "Docs" or "Documentation" word is used more than "Manual", right?.
I was looking for the "Docs" word in the menu, I couldn't find it so I start to read the items one by one and I come across the "Manual" word and I said, "it's probably the docs page". I still wasn't sure😂, so after navigating to the manual page, I was like "Oh yeah, it's the docs page"😂.
That's why I created this issue so it never happens again for some other users.

**Comment by ayoreis** [comment]
Deno Deploy calls it "Docs".

I think we can use "Manual" but then Deno Deploy should use it too.

**Comment by crowlKats** [comment]
Docs now has a different meaning with the work of rendering documentation of modules, so closing

**Comment by crowlKats** [comment]
So we are currently undergoing an effort of providing documentation of individual /x/ modules (the same way as if you currently go to https://deno.land/std/collections/), this basically is merging doc.deno.land into deno.land, so the terminology of docs would be documentation from third party (or std) modules.
On the other hand, the manual is that, a manual, aka an instruction book. If i had to make a comparison:
Deno Manual = Rust Book
doc.deno.land (and as such, the concept of docs through that) = docs.rs
