### ISSUE TITLE
Add `.ts` `.js` language toggle to code block

### ISSUE THREAD

**Issue by babakfp** [denoland/dotland#1934]
[Live Example](https://docs.nestjs.com/first-steps)
![Annotation 2021-11-08 181406-min](https://user-images.githubusercontent.com/44144724/140763583-9ff1f461-ddff-4ee6-a6a8-35e09e0fd9dd.png)

### What is the benefit?
Not everyone uses, cares, or likes Typescript. Let's say I don't know ts, then the code is going to be very confusing, hard to read, and repulsive to me. I may even drop the Deno and go to the Node's big muscular sexy arms.
What if?... What if the language toggle were available? Then I can just look at the code that I'm familiar with. Then probably I would stick with Deno (for now).
It just makes the Deno so much hard for the beginners or the people that don't know ts.
I believe it's a valuable move to add this feature.
It's important not to forget to update both languages when editing the code block content.

Thanks.

**Comment by crowlKats** [comment]
Closing as potentially very complex for little added benefit
