### ISSUE TITLE
Deno blog gives 404 if URL has trailing slash

### ISSUE THREAD

**Issue by josephrocca** [denoland/dotland#1939]
The top result for "deno mdn" on Google is the deno blog:

![image](https://user-images.githubusercontent.com/1167575/141516650-4e6db4e8-7567-48fd-a917-ae4adcf7dd75.png)

But it gives a 404 due to the trailing slash in the URL. I'm guessing there was a recent update to the website which broke this, and Google will re-index the non-trailing-slash URLs eventually, but it seems like a good idea to allow trailing slashes on URLs or redirect them to non-trailing-slash URL instead of throwing a 404.

Note that https://deno.com/blog/ has the same problem (i.e. it's not just the individual blog posts).

**Comment by EdJoPaTo** [comment]
This is also the reason why my RSS feed reader got stuck on `https://deno.com/feed/`. Removing the trailing slash works but is still dumb to find out.
Especially as the https://deno.com/blog webpage doesnt indicate the correct RSS Link via a visible link or header (`<link rel="alternate" type="application/rss+xml" href="/feed" title="Deno" />`)

**Comment by kidonng** [comment]
This is not the repository for `deno.com` but `deno.land`. I suppose you will get more luck asking this on the Discord.

**Comment by lucacasonato** [comment]
We are working on it!

**Comment by lucacasonato** [comment]
This is now fixed!

**Comment by lucacasonato** [comment]
> Especially as the https://deno.com/blog webpage doesnt indicate the correct RSS Link via a visible link or header (`<link rel="alternate" type="application/rss+xml" href="/feed" title="Deno" />`)

This is now also fixed. I have added a rel=alternate link tag :-)
