### ISSUE TITLE
Weird completions for 'https://deno.land/std@0.120.0/'

### ISSUE THREAD

**Issue by imjamesb** [denoland/dotland#1987]
issue cause

![image](https://user-images.githubusercontent.com/35933830/148548102-e714b031-4df7-4fbf-96ec-bd4154733f3e.png)

![image](https://user-images.githubusercontent.com/35933830/148547840-c75ec84d-624f-4a14-a618-c5e13bd28b3a.png)

![image](https://user-images.githubusercontent.com/35933830/148547968-ad06d201-02f4-4ed1-8833-eb92e891e793.png)

.vscode settings

```json
{
	"deno.enable": true,
	"deno.lint": true,
	"deno.unstable": false,
	"editor.insertSpaces": true,
	"editor.tabSize": 2,
	"[typescript]": {
		"editor.defaultFormatter": "denoland.vscode-deno"
	},
	"[json]": {
		"editor.defaultFormatter": "denoland.vscode-deno"
	},
	"deno.suggest.imports.hosts": {
		"https://deno.land": true,
		"https://crux.land": true
	},
  "[css]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "deno.config": "./deno.jsonc"
}
```

denoc.json

```json
{
  "compilerOptions": {
    "lib": [
      "deno.window",
      "dom"
    ]
  }
}
```

**Comment by kitsonk** [comment]
What happens when you update to Deno 1.17.3?

**Comment by ihack2712** [comment]
This also seems to be an issue on 1.17.1

![image](https://user-images.githubusercontent.com/35933830/148642199-77f72b2e-2217-48c7-86d6-96b4dbfdc4d4.png)


@kitsonk don't know i'll try

**Comment by ihack2712** [comment]
@kitsonk Latest version is 1.17.2 according to deno upgrade, should I upgrade with unstable?

**Comment by kitsonk** [comment]
Sorry... 1.7.2 was the latest.  I was confused...

**Comment by crowlKats** [comment]
This doesnt seem to be the case anymore as per author, so closing
