### ISSUE TITLE
Multiple tags with same name causing problem in pinning

### ISSUE THREAD

**Issue by Heikrana** [denoland/dotland#2003]
In the manual page [3.4 Web Platform APIs](https://deno.land/manual@v1.18.2/runtime/web_platform_apis#overview). There are 2 `overview` tags.
When you pin the first tag, it works. But when you pin the second tag, it results in pinning the first tag. It's an easy fix. just give seprate IDs to those tags (I think).

Can I do this?

**Comment by lucacasonato** [comment]
Yeah, sounds good!

**Comment by Heikrana** [comment]
I have a small problem, when I use the command `yarn install` to install the dependencies... it shows these warnings,
![yarn_install](https://user-images.githubusercontent.com/49754221/153094028-0425bef8-6eed-4a88-8cc3-09fc935bbe98.png)
and when I try to run `yarn dev` it shows this error, 
![Screenshot_20220209_051438](https://user-images.githubusercontent.com/49754221/153094595-3d2f9d73-2323-4e92-8aa7-388418562a30.png)

**Comment by crowlKats** [comment]
This is not an issue anymore, so closing
