### ISSUE TITLE
Better documentation experience for /x

### ISSUE THREAD

**Issue by lucacasonato** [denoland/dotland#2008]
Currently finding documentation for modules is not a great experience. You have to click through the module file explorer, find the source file you care about, click on it (at which point you are greeted by a wall of source text), and then click on the tiny "View Documentation" button that shows up above the source code. This is really not great.

Instead what if we do the following:

- we collapse the file explorer by default
- for directories, we show an overview of all of the exported symbols with 1 line of docs from each symbol. clicking on a symbol should link you to doc.deno.land.
- doc.deno.land should show an import statement to copy paste

**Comment by kitsonk** [comment]
We have this logic in the registry to select the likely "root" module of a package, which we would need to guess at for generating a doc link:

https://github.com/denoland/dotland/blob/061dcb5abe7b079a8bb7fa7d92a5c39f7fe2c3e4/worker/suggestions.ts#L227-L259

**Comment by crowlKats** [comment]
We have been working towards this, and are past what was originally proposed, so closing as further problems should have their own issues
