### ISSUE TITLE
Not requiring specific versions results in lots of broken modules

### ISSUE THREAD

**Issue by justinmchase** [denoland/dotland#2011]
I keep trying to use modules only to find they have imported some other module without specifying a version (or any tag) in their import url and that module has published a breaking change in their latest version.

Its very frustrating and leads to a perception of Deno being broken in general. I know this isn't really a deno bug, as its just pulling down whats coming from the server and there are lockfile options to help prevent that kind of issue but to whatever extent dotland can prevent this issue from propagating in simple 3rd party libraries I think it should.

I would recommend removing any features in dotland which would attempt to serve up a default tag (latest) or infer a default module (mod.ts) and require a user to specifically give a full path to their module including the tag.

For backwards compatibility maybe scan all the modules you currently have cached and do the inference one last time and bake it into a file? Every current module without a version identifier would get that one specific version in perpetuity plus a x-deno-warning to update your imports. I can't think of anything better without just hard breaking everyone doing this right now. 

But, it really sucks not to have versions on your deps.

**Comment by crowlKats** [comment]
We will not remove the ability to use a default tag (and we dont have a default module fallback). However, to aid this issue, we have recently added a list of dependencies used by a module, so you can tell if it is using a version implicitly or not.

**Comment by justinmchase** [comment]
Is there a way to do version locking? I don't really care per-se if it doesn't have a specific version so long as I can lock the version at a point in time. Its when they referencing things like std library which ends up taking on breaking changes as deno evolves and it breaks running code, that is painful. But if I could lock it that would help quite a bit.
