### ISSUE TITLE
Migrate to fresh refactor

### ISSUE THREAD

**Issue by ry** [denoland/dotland#2017]
- [x] Finish and land https://github.com/denoland/dotland/pull/2016
- [x] Unlink github repo from vercel project - so it doesn't get inadvertently updated  
- [x]  Update Deploy project dotland-fresh.deno.dev to point to main instead fresh branch. (unlink then link)
- [x] Update [`REMOTE_URL`](https://github.com/denoland/dotland/blob/453450c5b3ef987f45fe3fc34b8d2ad503591447/worker/handler.ts#L12) to be `dotland-fresh.deno.dev`. This removes dependency on vercel. https://github.com/denoland/dotland/pull/2019
- [x] Start new PR that merges worker and fresh code into single code base. https://github.com/denoland/dotland/pull/2020
- [x] Merge PR and update dotland project to point to main.ts instead of worker/main.ts ... These two steps must happen very quickly. (Symlink? Does that work?)
- [x] Delete dotland-fresh deploy project.

**Comment by vwkd** [comment]
Nit: Update README.md
