### ISSUE TITLE
Improve pagespeed score 

### ISSUE THREAD

**Issue by ry** [denoland/dotland#2021]
This is for https://deno.land/x/oak@v10.4.0/application.ts

<img width="636" alt="Screen Shot 2022-02-23 at 8 48 13 PM" src="https://user-images.githubusercontent.com/80/155441667-cefd8464-a602-459f-8597-97e5d1e8a79c.png">

https://pagespeed.web.dev/report?url=https%3A%2F%2Fdeno.land%2Fx%2Foak%40v10.4.0%2Fapplication.ts

**Comment by satyarohith** [comment]
Automatic response body compression improved the lighthouse score.

![CleanShot 2022-03-07 at 01 30 15@2x](https://user-images.githubusercontent.com/29819102/156940034-aa43ad36-9ca9-4b75-ae73-652bbe9b4a12.png)

**Comment by ry** [comment]
Improved!
