### ISSUE TITLE
HTML5 details/summary not rendering correctly

### ISSUE THREAD

**Issue by SheetJSDev** [denoland/dotland#2059]
Compare https://github.com/SheetJS/sheetjs#table-of-contents with https://deno.land/x/sheetjs@v0.18.3#table-of-contents

GitHub recognizes the HTML5 details block (the `▶` denotes a closed details block):

<img width="307" alt="Screen Shot 2022-03-11 at 3 52 07 AM" src="https://user-images.githubusercontent.com/6070939/157834304-6796614d-3938-4d75-9461-3aec9d37f924.png">

deno.land does not

<img width="291" alt="Screen Shot 2022-03-11 at 3 52 27 AM" src="https://user-images.githubusercontent.com/6070939/157834344-c0c96aee-086f-419c-b628-d53738975320.png">

**Comment by LeoDog896** [comment]
Should be fixed in downstream PR: https://github.com/lucacasonato/deno-gfm/pull/25
