### ISSUE TITLE
Some deno.land links are broken 

### ISSUE THREAD

**Issue by sigmaSd** [denoland/dotland#2063]
## 404 but has version - #2064 
- https://deno.land/x/xtr
- https://deno.land/x/dxf
- https://deno.land/x/dxr
- https://deno.land/x/dexter

## Directory not found:
- https://deno.land/x/vscode_languageserver_protocol

## 502
- https://deno.land/x/axe
- https://deno.land/x/lent
- https://deno.land/x/dxi 
- https://deno.land/x/deenvo

**Comment by crowlKats** [comment]
The ones that come in search but give 404 are weird; they have a null `versions`. Modules that exist but have no version are to be `{latest: null, versions: []}`, so this is quite weird. @lucacasonato

**Comment by kidonng** [comment]
Yesterday https://deno.land/std@0.110.0/path/mod.ts reports 404 for me. Now it doesn't, but shows the code in wrong format:

<img width="933" alt="image" src="https://user-images.githubusercontent.com/44045911/159881461-cb6b1d6c-9368-4461-9bd1-029561ffcc80.png">

**Comment by kitsonk** [comment]
looks like all links to code are "broken"

**Comment by kidonng** [comment]
I don't know much about how Deno Deploy work, does it run the same code upon each request? If true, it's probably not the issue of website itself.

**Comment by hyp3rflow** [comment]
> Yesterday [deno.land/std@0.110.0/path/mod.ts](https://deno.land/std@0.110.0/path/mod.ts) reports 404 for me. Now it doesn't, but shows the code in wrong format:

This seems to be resolved now. isn't it?
<img width="936" alt="image" src="https://user-images.githubusercontent.com/49385012/160055860-77bab6db-70a6-4529-a5cb-69e487144b35.png">

**Comment by crowlKats** [comment]
@hyp3rflow yes, this was fixed

**Comment by sigmaSd** [comment]
seems to be fixed
