### ISSUE TITLE
Readme not rendering for `std/testing`

### ISSUE THREAD

**Issue by jespertheend** [denoland/dotland#2066]
When I visit https://deno.land/std@0.129.0/testing the readme is not visible, even though `README.md` is bold.
Other folders with a readme seem to work fine.

![image](https://user-images.githubusercontent.com/2737650/158487203-35798c13-b642-496e-b4f0-7035e4ca9651.png)

**Comment by jespertheend** [comment]
Seems like `std/testing` is not the only page with this issue:
- https://deno.land/std
- https://deno.land/std@0.129.0/http
- https://deno.land/std@0.129.0/path

Others are still fine, https://deno.land/std@0.129.0/uuid for instance

**Comment by crowlKats** [comment]
Closed by #2067
