### ISSUE TITLE
wrong readme selected to be shown

### ISSUE THREAD

**Issue by panva** [denoland/dotland#2069]
Expectation: When present, the root readme file is rendered in favour of other subpath-present readme files.

Reality: The first `README.md` file found in the dir listing regardless of it being in a subpath is used.

See https://deno.land/x/doauth where `docs/README.md` file is used, instead of the `README.md` in the root of the project.

**Comment by crowlKats** [comment]
> > maybe we should prioritize root README, and then go to those aforementioned directories
> 
> I agree. If you'd point me to the right place I'd give a PR a shot.

https://github.com/denoland/dotland/blob/main/util/registry_utils.ts#L336-L351, this is the function that finds the readme
