### ISSUE TITLE
Deno manual 502: Bad Gateway (DEPLOYMENT_FAILED) The deployment failed while serving the request.

### ISSUE THREAD

**Issue by ayoreis** [denoland/dotland#2079]
Today I wanted to go learn more about testing in Deno and found the manual page (other pages seem to work) is giving a 502 error:

<img width="960" alt="image" src="https://user-images.githubusercontent.com/84969551/159301694-9f09f2ab-261c-414f-955e-6d292173e4aa.png">

**Comment by kitsonk** [comment]
It appears to have been a transitive issue. Is it working for you now?

**Comment by ayoreis** [comment]
Yes.
