### ISSUE TITLE
Improve scoring of packages

### ISSUE THREAD

**Issue by kitsonk** [denoland/dotland#2081]
Currently, the landing page for `deno.land/x` lists packages in GitHub star priority. Things like oak, one of the most popular Deno specific projects, doesn't appear on the landing page. We should improve the scoring to reflect applicability to Deno, as well as provide that information to users to be able to better discover packages.

**Comment by KnorpelSenf** [comment]
Do you collect statistics about how often a file is downloaded via CLI, how often a module is found via search, or how often a module's main page/README is visited via browser?

If not, what are you planning on using as a metric to decide which packages to show?

**Comment by kitsonk** [comment]
Tracked by #2133
