### ISSUE TITLE
Use releases as x-axis in benchmarks

### ISSUE THREAD

**Issue by zlumyo** [denoland/dotland#2083]
[Benchmarks on landing page](https://deno.land/benchmarks) use commits as x-axis. IMHO, for average visiter it's more natural to see progress through releases instead of countless and (often) meaningless commits. Or at least provide a switch between two modes.

**Comment by kitsonk** [comment]
If we limited it to releases, we would not see what specific commits improved or regressed performance. While it is part of the public website, it really isn't designed to be a "marketing tool" for Deno, but to provide critical information to the people building Deno.

**Comment by zlumyo** [comment]
Of course, for a developer or an advanced user commits are more valuable. So if these benchmarks isn't design to be a "marketing tool" (although it could be), this discussion can be closed.

**Comment by crowlKats** [comment]
Closing due to points provided by Kitson.
