### ISSUE TITLE
Deno third party module not callable under certain circumstances

### ISSUE THREAD

**Issue by piuswalter** [denoland/dotland#2091]
Hello all,

we found some interesting bug while publishing a new third party module for Deno. After publishing the module we try to call it the deno.land standard way with `https://deno.land/x/<module name>`. So if we call `lodash` ([https://deno.land/x/lodash](https://deno.land/x/lodash)) this way, we get the module page. If we call our new module `svelte_tailwind_widgets` ([https://deno.land/x/svelte_tailwind_widgets](https://deno.land/x/svelte_tailwind_widgets)) this way, we get an error page.

Now the curious part begins. If we call our module with an ending slash ([https://deno.land/x/svelte_tailwind_widgets/](https://deno.land/x/svelte_tailwind_widgets/)) or with an given version ([https://deno.land/x/svelte_tailwind_widgets@v1.0.0](https://deno.land/x/svelte_tailwind_widgets@v1.0.0)) we can reach it without any error message. How is that possible?

The problem is that if we search for our module, then the broken link is used to navigate us to the error page.

**Comment by crowlKats** [comment]
I tried to reproduce, but for me all links just work, even the result from /x/ for said module name.

**Comment by piuswalter** [comment]
Thank you for the fast response! If I try calling [https://deno.land/x/svelte_tailwind_widgets](https://deno.land/x/svelte_tailwind_widgets), I get the following error message:
```
No uploaded versions
This module name has been reserved for a repository, but no versions have been uploaded yet. Modules that do not upload a version within 30 days of registration will be removed. 
```

**Comment by crowlKats** [comment]
Oh, I see. It seems this is our stupid caching kicking in; this has been getting quite out of hand recently, we need to address this quickly.

**Comment by crowlKats** [comment]
Closing as things have changes and should be better now.
