### ISSUE TITLE
Add interactive links to symbols in the code

### ISSUE THREAD

**Issue by KnorpelSenf** [denoland/dotland#2098]
We already have TypeScript and we have the necessary tooling to analyse where a symbol is defined.

It would be amazing if we had a simple go-to definition functionality in the website. In other words, clicking on a type annotation with an interface `Q` will open the file containing the definition of `Q` and scroll to the line of code.

This is probably a lot of work, but IMO it's also a lot of benefit.

**Comment by KnorpelSenf** [comment]
It would also be nice to have tooltips with the JSDoc of the element when hovering above it.

**Comment by crowlKats** [comment]
Closing as this is implemented
