### ISSUE TITLE
Pagination and Sorting

### ISSUE THREAD

**Issue by Industrial** [denoland/dotland#2104]
Hello.

Please add pagination and sorting to https://deno.land/x. Without it, you are looking through a list looking for the entries with the most stars, sorting them by stars in your head and then you can't go to the next page. This feels like a let down :-1:

**Comment by Industrial** [comment]
Is there an API call that can be made to list packages that returns JSON?

**Comment by lucacasonato** [comment]
The page has pagination: https://deno.land/x?page=3

**Comment by lucacasonato** [comment]
> Is there an API call that can be made to list packages that returns JSON?

https://github.com/denoland/deno_registry2/blob/main/API.md#get-modules

**Comment by meszarosdezso** [comment]
@Industrial I assume you are talking about _searching_ in the registry. Like on https://deno.land/x?query=deno there's no pagination or sorting indeed, but I agree it would be a nice UX improvement. I will look into the pagination part, I guess the sorting should be handled in [denoland/deno_registry2](https://github.com/denoland/deno_registry2) (?)

**Comment by Industrial** [comment]
Yes, I am talking about sorting and pagination in the UI. Having sorting would make it easier to glance what the community is leaning towards for solving problems and pagination for knowing what else is out there.

**Comment by crowlKats** [comment]
Search has been fixed
