### ISSUE TITLE
Several manual links broken

### ISSUE THREAD

**Issue by ayoreis** [denoland/dotland#2128]
Example in [Using JSX and the DOM](https://deno.land/manual@v1.21.1/jsx_dom) when clicking on [Overview of JSX and DOM in Deno](https://deno.land/manual@v1.21.1/jsx_dom/jsx_dom/overview.md) it goes to [jsx_dom/jsx_dom/overview.md](https://deno.land/manual@v1.21.1/jsx_dom/jsx_dom/overview.md) (which throws a 404 error) instead of [jsx_dom/overview](https://deno.land/manual@v1.21.1/jsx_dom/overview) or [jsx_dom/overview.md](https://deno.land/manual@v1.21.1/jsx_dom/overview.md) (which both work).

This problem only occurs for the ["Table of contents"](https://deno.land/manual@v1.21.1/jsx_dom/) links and not the ones in the sidebar. This happens on many other pages, but not all.

**Comment by ry** [comment]
PRs welcome!

**Comment by ayoreis** [comment]
I’ll try tomorrow.

**Comment by ayoreis** [comment]
Should the URLs ending in `.md` work too?

**Comment by bartlomieju** [comment]
> Should the URLs ending in `.md` work too?

No, it's an implementation detail that users shouldn't be concerned with.

**Comment by ayoreis** [comment]
Not sure what happened but the links are now working? (local and on [deno.land/manual](https://deno.land/manual)) I'm sure yesterday they where not, triple checked in different browsers, so not sure what even try fixing.

Though I found the [deno-dom](https://deno.land/x/deno_dom) link had a typo, that's fixed with this PR I made: https://github.com/denoland/manual/pull/310

**Comment by ayoreis** [comment]
> > Should the URLs ending in `.md` work too?
> 
> No, it's an implementation detail that users shouldn't be concerned with.

Can I try fixing it?

**Comment by bartlomieju** [comment]
Sure!

**Comment by ayoreis** [comment]
**UPDATE:** turns out this has already been "fixed" ([here]( https://github.com/denoland/dotland/blob/main/routes/manual.tsx#:~:text=if%20(url.pathname,%7D )) before when you switched over to Fresh. And on local it really is though not the actual website. I think it has to do by the website not being deployed to Deno Deploy yet: https://github.com/denoland/manual/pull/10

**Comment by crowlKats** [comment]
This should be fixed now, so closing
