### ISSUE TITLE
Persist `dirview` / `codeview` preference for `std` between page renders

### ISSUE THREAD

**Issue by curtislarson** [denoland/dotland#2180]
I prefer the `dirview` and `codeview` style when viewing docs for `std` but the search params are not persisted when navigating through the documentation which makes those settings pretty much unusable.

Is this a bug or something that is planned to be supported? Let me know if you need more information and I'm happy to work on a PR for the change.

**Comment by bartlomieju** [comment]
PRs welcome, this just hasn't been implemented yet.

**Comment by imjamesb** [comment]
IMO persistence between page renders should be everywhere ;)

**Comment by crowlKats** [comment]
Given the changes of design and functionality, closing as not necessary anymore
