### ISSUE TITLE
auto generated docs seem to confuse

### ISSUE THREAD

**Issue by michael-spengler** [denoland/dotland#2183]
Hi. This is probably for @lucacasonato as it is about the third party module registry.... 
Can I somehow avoid the autogeneration which was introduced lately because it's rather confusing than helpful? --> 

My readme documented things perfectly fine already imo ... now it looks confusing for the visitor of e.g. https://deno.land/x/bollinger_bands@v0.2.0

**Comment by kidonng** [comment]
Apart from the issue mentioned in #2180, there's no way to fold the "deno doc" section, or jump to README directly.

**Comment by crowlKats** [comment]
Closing in favour of #2407
