### ISSUE TITLE
Center the current file in the sidebar by default

### ISSUE THREAD

**Issue by orta** [denoland/dotland#2189]
I loaded up https://deno.land/manual/examples/read_write_files via search and had no frame of reference for where I was in the docs.

The request would make: 

![image](https://user-images.githubusercontent.com/49038/174964858-1787a262-cbf6-4e57-aa84-fbc8bccf04bf.png)

Instead be:

![image](https://user-images.githubusercontent.com/49038/174964945-3e4d6a4a-7c2c-4c94-9701-34fa219605f8.png)

**Comment by crowlKats** [comment]
to be clear, what you are asking for is that we scroll the table of contents so that the current viewed entry is visible in it?

**Comment by orta** [comment]
Yes
