### ISSUE TITLE
Server push

### ISSUE THREAD

**Issue by mfulton26** [denoland/dotland#2205]
As dependency trees get deeper I'd like to see my Deno apps still load from no cache very quickly.

Today as I understand it the first (entry point) module is downloaded and then Deno identifies import statements and then starts downloading the next modules. The deeper the tree of dependencies the more time waiting to determine what modules to request next.

What I think I'd like to see is for Deno registry to push all dependencies to the client. If a client already has certain resources cached then it can cancel the push promises. This might be overkill for when most of the cache is already populated. Perhaps a flag is sent on the initial request signaling an opt-in to such functionality but that might not be necessary as cancelling pushes might suffice (a small bandwidth cost for low latency guarantees).

I think this would be useful for fresh development containers where there is no cache yet, CI/CD pipelines with limited or no caches, etc.

Ultimately it means that developers need to worry less about how deep the tree of dependencies gets (or how small and many modules they make) and not be concerned with creating build steps that pre-bundle things, etc. but can point to an entry module and know that it will quickly load even from nothing yet cached.

**Comment by lucacasonato** [comment]
Server push is not supported in any browser anymore, and Deno does not support it either. H2 server push is dead: https://evertpot.com/http-2-push-is-dead/.

Best we could do is have deno support `Link: rel=preload` headers, but that should start out as a feature suggestion on denoland/deno.

**Comment by mfulton26** [comment]
I had no idea. 🤯

Thank you for enlightening me!
