### ISSUE TITLE
bug: /x doesn't format markdown strikethroughs

### ISSUE THREAD

**Issue by retraigo** [denoland/dotland#2217]
The \~\~strikethrough\~\~ doesn't seem to be formatted in /x.

GitHub:
![Screenshot_20220628_230105](https://user-images.githubusercontent.com/56877379/176246132-d39fbe58-e99d-4bb8-bcdc-ca328d8b2138.png)

dotland/x:
![Screenshot_20220628_230132](https://user-images.githubusercontent.com/56877379/176246231-c8ff89cd-7d9a-4987-99b3-fb1bcf4c6361.png)

**Comment by LeoDog896** [comment]
Should be fixed in new PR: https://github.com/lucacasonato/deno-gfm/pull/25
