### ISSUE TITLE
Ability to see documentation on package page.

### ISSUE THREAD

**Issue by jukefr** [denoland/dotland#2232]
Maybe this is already possible and if so I am sorry, I could not find anything documenting this.

The idea is to have deno package landing pages display the same format as the std package landing page, with the documentation view in place of the repository file view.

If i go to https://deno.land/std@0.146.0 I get the https://doc.deno.land view on the package page directly.

I tried to reproduce this here https://deno.land/x/readme_manager@v2.6.0, I saw that there was a comment with the `@module` jsdoc decorator and figured this was what toggled it but no.

The docs are generated correctly on https://doc.deno.land/https://deno.land/x/readme_manager@v2.6.0, I would just like to have them show directly on the package page just like the std package does.

Is this possible ?

**Comment by crowlKats** [comment]
we currently disabled doc view for third party modules due to performance issues and incompleteness of this new system. once the doc based view is done & usable, we will enable it for all modules

**Comment by jukefr** [comment]
Thanks for the heads up
