### ISSUE TITLE
non-docable files error out doc page

### ISSUE THREAD

**Issue by crowlKats** [denoland/dotland#2263]
Any non-docable file will error out the page, ie https://deno.land/std@0.136.0/Releases.md. these should redirect to their code alternative. 
https://github.com/denoland/dotland/blob/22925d0ee7f8e0b5c1669ebc9aaa8b7c7843e940/util/doc.ts#L36

**Comment by kidonng** [comment]
I was going to report this a few days ago 😅 note this only applies to `/std`, not `/x`.

**Comment by crowlKats** [comment]
yea, though this would apply to `/x` as soon as we enable docs there, which hopefully isnt too far off. quick-fix would be try-catch the whole content of the function and return null if there is an error

**Comment by crowlKats** [comment]
Closing as addressed
