### ISSUE TITLE
/std readme.md `$STD_VERSION` not substituted

### ISSUE THREAD

**Issue by jespertheend** [denoland/dotland#2271]
For example at https://deno.land/std@0.148.0/path
it still shows
```js
import * as path from "https://deno.land/std@$STD_VERSION/path/mod.ts";
```

**Comment by crowlKats** [comment]
No, that issue is different. this is surprising that this is happening, will look into it

**Comment by jespertheend** [comment]
Huh, this seems to have been fixed just now

**Comment by crowlKats** [comment]
Closing as seems to be fixed
