### ISSUE TITLE
https://deno.land is down

### ISSUE THREAD

**Issue by jaydenseric** [denoland/dotland#2272]
https://deno.land/ is down:

<img width="686" alt="Screen Shot 2022-07-18 at 10 33 21 am" src="https://user-images.githubusercontent.com/1754873/179431301-07d00b29-fc50-4b2b-b9ae-62107de2293c.png">

Potentially a huge problem for apps depending on the packages served at `/x/`, e.g https://deno.land/x/ruck@v6.0.0/serve.mjs :

<img width="840" alt="Screen Shot 2022-07-18 at 10 39 29 am" src="https://user-images.githubusercontent.com/1754873/179431417-93ba7f0b-c503-45f1-bc0c-f852a7ff68b3.png">

**Comment by jaydenseric** [comment]
Discord:

https://discord.com/channels/684898665143206084/989436517518802945/998387109725478922

Deno Deploy outage details:

https://denostatus.com

**Comment by kitsonk** [comment]
https://denostatus.com/ is the location where information is managed about this. There is no need to raise an issue.

A retrospective of the outage will be available in a while on https://deno.land/blog.
