### ISSUE TITLE
Invalid image size rendering in README's

### ISSUE THREAD

**Issue by Im-Beast** [denoland/dotland#2279]
`deno.land/x` seems to overwrite height of images to `auto` which breaks images in README that specify `width` or `height` attributes.

On the top how it's supposed to look like (how github renders it) and on the bottom how it looks like.

![image](https://user-images.githubusercontent.com/47059999/179736658-3095cb47-ecfe-4305-b408-427f4d220ecb.png)
![image](https://user-images.githubusercontent.com/47059999/179736696-f0dea40f-7fc8-49f5-92ae-194528818510.png)

**Comment by st-lr-c** [comment]
last
