### ISSUE TITLE
/std class methods are not documented

### ISSUE THREAD

**Issue by jespertheend** [denoland/dotland#2285]
For example on https://deno.land/std@0.149.0/http/server.ts?s=Server

You can see the available methods of the class, but their descriptions are missing.

The same page for comparison on doc.deno.land:
https://doc.deno.land/https://deno.land/std@0.149.0/http/server.ts/~/Server

I wasn't able to find any other way to view the descriptions of any class method either.

**Comment by kitsonk** [comment]
Currently this is expected, as the symbol documentation is a work in progress.  Apologies that there is confusion and some bumpy roads as we continue to evolve the documentation. We should start landing more complete symbol documentation over the next week.

**Comment by crowlKats** [comment]
This should be addressed now; we are still iterating to improving it though
