### ISSUE TITLE
Missing hover states

### ISSUE THREAD

**Issue by lucacasonato** [denoland/dotland#2309]
There are a bunch of items across the page that are either missing hover states, or where the hover state is not very accessible:

- [x] "Go to Latest" button on the module page
- [x] Version dropdown on the module page
- [x] All the links & buttons on the code source view (the hover states are not pronounced enough)
- [x] Social logos in the footer
- [x] Social logos in the header
- [x] Search bar in the header
- [x] Links in the manual sidebar
- [ ] "Open & Close" chevron in the manual sidebar
- [x] Edit button in the manual

As a general rule of thumb, the hover state should either be something like an underline (works really well for links), or it should have a very pronounced contrast change (works well for buttons).

**Comment by crowlKats** [comment]
>  Links in the manual sidebar

The ToC does have hover for the text; for the current selected, the blue is the same we use for "normal" links
