### ISSUE TITLE
[feat] hide hidden files in directory listing

### ISSUE THREAD

**Issue by brandonkal** [denoland/dotland#231]
These files can still be served from the proxy and via direct link, but it would make sense to exclude these files from the listing, maybe adding a button at the bottom of the list:
"Show 3 hidden items"

**Comment by divy-work** [comment]
I was looking forward to contributing or is there a PR already?

**Comment by lucacasonato** [comment]
@divy-work This has not been taken by anyone yet, so feel free to work on it.

**Comment by crowlKats** [comment]
This was implemented in the linked PR.
