### ISSUE TITLE
Unexpected black frame around the instatus button in the footer 

### ISSUE THREAD

**Issue by roj1512** [denoland/dotland#2323]

**Comment by kitsonk** [comment]
![Deno_-_A_modern_runtime_for_JavaScript_and_TypeScript](https://user-images.githubusercontent.com/1282577/181405547-f33b75a1-00e8-44f3-bb05-74f2112da0dd.png)

**Comment by meszarosdezso** [comment]
It's beacause the embedded iframe's (https://denostatus.com/embed-status/light-sm) html automatically has `color-scheme: dark` (instatus follows the system dark mode). _I think_ it's configurable in the instatus dashboard.
