### ISSUE TITLE
Placeholder too long on mobile

### ISSUE THREAD

**Issue by kidonng** [denoland/dotland#2324]
I feel the words are redundant as they can be seen in the tab just below.

<img width="454" alt="image" src="https://user-images.githubusercontent.com/44045911/181217714-ed26c303-5e56-4758-9a60-7f472c9a2b79.png">

**Comment by Thisisaarush** [comment]
styling it with `...`  at the end would make sense?

**Comment by kidonng** [comment]
This has been fixed at some time:

<img width="412" alt="image" src="https://user-images.githubusercontent.com/44045911/232266224-544a271a-574c-407f-b6f9-9755ad324fb6.png">
