### ISSUE TITLE
Edit button in manual has inappropriate position

### ISSUE THREAD

**Issue by kidonng** [denoland/dotland#2325]
The edit button in manual looks right when the first heading is a `<h1>`:

<img width="898" alt="image" src="https://user-images.githubusercontent.com/44045911/181218009-674a5527-47dc-46d6-a6c7-533ed5b2f72c.png">

But not for a `<h2>`:

<img width="906" alt="image" src="https://user-images.githubusercontent.com/44045911/181218044-c671534f-3c06-4350-b6ea-7857bc7f3f84.png">

Whether this is a bug depends on how you see it. I feel the `<h2>`s should be change in `<h1>` in the source files.

**Comment by crowlKats** [comment]
This is right behaviour, so closing. Might make sense to open an issue in the manual about adjusting headers
