### ISSUE TITLE
Search modal blocks page on Safari

### ISSUE THREAD

**Issue by blakechambers** [denoland/dotland#2332]
It looks like the search modal is blocking page content when browsing the side using Safari.  Here's what it looks like loading the https://deno.land page:

<img width="1356" alt="Screen Shot 2022-07-30 at 8 15 35 AM" src="https://user-images.githubusercontent.com/46827/181913928-07098db3-9633-4d9d-ac76-820d34811e3a.png">

The modal doesn't seem to be dismissible (I tried hitting ESC and clicking away from the search box).  The page doesn't seem to have any javascript errors.  From some spot checking, it looks like it's on any page on the site, third party modules, and the docs.

I tried Chrome and see that the page looks to load normally.  

#### Details

- Safari Version 15.2 (16612.3.6.1.8, 16612)

**Comment by lucacasonato** [comment]
Should be fixed now.

**Comment by blakechambers** [comment]
Thank you!

**Comment by blakechambers** [comment]
Just wanted to note that this bug looks to be back on a couple pages – specifically on the https://deno.land/ and https://deno.land/x page (just the third party modules landing page, browsing individual modules seems to work).

**Comment by crowlKats** [comment]
@blakechambers is this still the case?

**Comment by blakechambers** [comment]
@crowlKats Everything looks like it's working now.  Thanks!
