### ISSUE TITLE
ui: header description feels "crowded"

### ISSUE THREAD

**Issue by kitsonk** [denoland/dotland#2352]
Displaying the module path with the description feels a bit crowded:

![jotai_v1_7_7___Deno](https://user-images.githubusercontent.com/1282577/182986271-22251906-0805-41e6-bbea-5bb5f51f28e5.png)

**Comment by crowlKats** [comment]
might need a bit more spacing between description and breaedcrumbs, and also spacing around the slashes, but besides that it seems fine to me

**Comment by kitsonk** [comment]
yeah, it was just a minor nit around spacing that I wanted to note...

**Comment by crowlKats** [comment]
This has been fixed
