### ISSUE TITLE
suggestion: prioritize projects with more stars in deno.land/x search

### ISSUE THREAD

**Issue by zachauten** [denoland/dotland#2353]
I searched for "oak" in deno.land/x, and it wasn't even on the front page of search results. It's in the top 30 or most starred deno projects, I don't think it makes sense that other search results with zero stars would be displayed ahead of it, especially considering that the name is an exact match with my search term.

**Comment by kitsonk** [comment]
We are reworking the whole of search for packages at the moment, and won't be using GitHub stats at all, but instead popularity of usage by the Deno CLI. It should land sometime next week.

**Comment by zachauten** [comment]
Very cool, thanks!
