### ISSUE TITLE
Handle built-in APIs

### ISSUE THREAD

**Issue by kitsonk** [denoland/dotland#2364]
We should consider handling built in APIs on deno.land like we do on docland: https://doc.deno.land/deno/stable as well as we should publish the doc node to algolia to integrate into the search.

**Comment by kitsonk** [comment]
Here is an example of what happens when searching for `WebSocket` which is common and clearly not the results we want to show:

<img width="1191" alt="Read_and_write_files___Manual___Deno" src="https://user-images.githubusercontent.com/1282577/183822103-be47bd73-f72e-4658-8c9f-cb1dfbe7a6d7.png">

**Comment by dsherret** [comment]
Another example with `Deno.run` and `run`.
![image](https://user-images.githubusercontent.com/1609021/189983085-648605a6-171f-4198-8335-82eda5eed6ad.png)
![image](https://user-images.githubusercontent.com/1609021/189983119-1d54b28f-9749-47ea-b286-80f23afd87f5.png)

**Comment by kitsonk** [comment]
This has landed.
