### ISSUE TITLE
Handle display of `@link` and `@linkcode` like dotland or vscode

### ISSUE THREAD

**Issue by kitsonk** [denoland/dotland#2371]
Currently, JSDoc tags `@link` and `@linkcode` in markdown on dotland don't operate as expected.  They render as `{@link stringify}` for example.  They need to generate a link to the symbol in the source module they originate from, or if for some reason that can't be resolved, just rendered as text (or `<code></code>` in the case of `@linkcode`).

**Comment by crowlKats** [comment]
Closing as fixed
