### ISSUE TITLE
Provide a module information page for 3rd party modules

### ISSUE THREAD

**Issue by kitsonk** [denoland/dotland#2383]
With the move to the new design, we have some challenges in how we display an "overview" of a module.  Currently when viewing a module you get one of two views:

- The module has a default module (like a `mod.ts` or an `index.js`) and that documentation for that module is displayed.
- The module doesn't have a default module in its root, and so we display an index view of the docable parts of the module.

If the index is displayed, we will provide a README if one is present after the index listing, and for the doc view of the default module, we currently only display the doc (see: #2376). Both of these _doc_ views have corresponding `?code` views.

We really need a info/overview of a module which allows us to provide the following information:

- A README if available prominently on the page.
- Details about when the version of the module was uploaded.
- Information about popularity, quality and maintenance of the module.
- Dependency information.
- Information about the Deno configuration file if detected.
- Links to the documentation view and source view of the module as well as the source repository.

We don't currently have a good way of doing this, but should have a solution.  Possibly where we `deno.land/info/:module@:version` would be the informational page above and `deno.land/source/:module@:version/:path*{/}?` would be the source view of the module, leaving `deno.land/x/:module@:version/:path*{/}?` to continue to be the doc view.

**Comment by crowlKats** [comment]
Closing as implemented
