### ISSUE TITLE
Issue with raw file links on deno.land/x

### ISSUE THREAD

**Issue by GJZwiers** [denoland/dotland#2385]
Trying to download a raw code file from the registry is prevented in the browser (Firefox) due to an unencrypted connection.

Steps to reproduce:

- Go to [a module on /x](https://deno.land/x/mod@v2.3.7/mod.ts?code).
- Click on 'Raw'

It does not seem to happen for all files. For example [this lodash file can be downloded as raw without issue](https://deno.land/x/lodash@4.17.19/lodash.js?code).

Firefox version: 104.0b9

**Comment by kitsonk** [comment]
@crowlKats could this be because of the change to how we access the raw files?

**Comment by crowlKats** [comment]
@kitsonk yea, this is because we dont use the CDN anymore, and instead directly the s3 bucet which only is accessible via http

**Comment by kitsonk** [comment]
Well, that is going to be a problem, as browsers with a https connection won't allow the downgrade. Makes the links useless.

I hadn't appreciated it was just a redirect, I had assumed we would consume off S3 in Deploy for what we need but still provide a secure connection for serving of raw files.

**Comment by crowlKats** [comment]
it seems to me that we need to keep the CDN around sadly...

**Comment by kitsonk** [comment]
Yes.
