### ISSUE TITLE
Unable to add new module via website "Invalid Name/Name has been taken!"

### ISSUE THREAD

**Issue by reggi** [denoland/dotland#2393]
On this page here: https://deno.land/add_module

![issue](https://user-images.githubusercontent.com/296798/185575593-3ecc4f55-d55e-45d8-be5a-7adc88d149d3.gif)

**Comment by ayoreis** [comment]
I don't think this is a bug. You are using hyphens which are not allowed, you should use underscores instead.

**Comment by reggi** [comment]
@ayoreis you totally might be right here. the message however is super confusing 😹

**Comment by kitsonk** [comment]
It is a bug, we should be displaying a message that indicates the actual problem, that hyphens aren't allowed.
