### ISSUE TITLE
/x doesn't handle certain odd tags

### ISSUE THREAD

**Issue by roj1512** [denoland/dotland#2396]
Live example: https://deno.land/x/grammy_storages@%2540grammyjs%252Fstorage-prisma%25402.0.0/redis/src/mod.ts

**Comment by roj1512** [comment]
I am not sure but according to https://github.com/denoland/dotland/blob/86c27fc3941277e31a250605a9f58bd288335c55/routes/x/module.tsx#L50, the reason might be https://github.com/denoland/fresh/issues/577.

**Comment by kitsonk** [comment]
I think it is more an issue with the tag.

**Comment by kidonng** [comment]
I have dealt with similar thing in #1709, though the codebase has changed a lot since then.

**Comment by crowlKats** [comment]
this has been addressed
