### ISSUE TITLE
Feature Request: Have package name breadcrumb go to latest readme page

### ISSUE THREAD

**Issue by reggi** [denoland/dotland#2418]
When I'm on this page:

https://deno.land/x/htm@0.0.10/mod.tsx

![Screen Shot 2022-08-26 at 9 33 21 PM](https://user-images.githubusercontent.com/296798/187009137-34d47a6b-20c1-4f9b-a2f6-bd3a389b0173.png)

I'm trying to get to this page below, clicking the red line in the breadcrumb doesn't work.

https://deno.land/x/htm ($latest)

![Screen Shot 2022-08-26 at 9 35 39 PM](https://user-images.githubusercontent.com/296798/187009154-d7c81c54-6976-4cd3-b8c6-0718238f0cb5.png)

It doesn't seem intuitive right now with no way to get there.

**Comment by kitsonk** [comment]
Yeah, feels like we should go back to the module landing page.

**Comment by crowlKats** [comment]
Yes and no, this should go where it is currently going; else there is no way to return to root in doc/source view. there is an issue about this in the figma; we probably need to add a new button

**Comment by dragonwocky** [comment]
@crowlKats can't you return to root by just clicking where it says "default module"? It would make a lot more sense for the breadcrumb to match the URL and navigate to the landing page....
