### ISSUE TITLE
Markdown links rendered without ".md"

### ISSUE THREAD

**Issue by mfulton26** [denoland/dotland#2427]
Some (all?) "*.md" URLs are missing ".md" when rendered in the manual despite the source containing it.

e.g.

- manual page: https://deno.land/manual@v1.25.0/runtime/http_server_apis#websocket-support
- expected link: https://github.com/ricea/websocketstream-explainer/blob/master/README.md
- actual link: https://github.com/ricea/websocketstream-explainer/blob/master/README

This lands folks on 404 pages.

**Comment by crowlKats** [comment]
caused by #2177. cc @kidonng
