### ISSUE TITLE
Create versions using GitHub releases instead of tags

### ISSUE THREAD

**Issue by MiguelRipoll23** [denoland/dotland#2430]
The integration between GitHub and Deno Deploy is flawless, it works very well. After some time using Deno Land with third party modules in order to keep GitHub releases and Deno Land versions completely synchronized it would be better to use releases instead of tags to publish a new version.

This also opens the possibility to use the pre-release flag from GitHub in Deno Land as well or combine other actions to publish to an alternative registry like GitHub Packages.

Thank you, ❤️ Deno.

**Comment by kitsonk** [comment]
Thank you, but we will stick with tags. GitHub releases are GitHub specific and simply an overlay on git tags. Git tags are universal in the git ecosystem and help ensure that we will not always be limited to GitHub in the future.

Respectfully declined.
