### ISSUE TITLE
Invalid symbols show "404 module not found" error

### ISSUE THREAD

**Issue by lucacasonato** [denoland/dotland#2436]
See https://deno.land/x/fresh@1.0.2/server.ts?s=Plugin.

<img width="618" alt="image" src="https://user-images.githubusercontent.com/7829205/187670090-8298ae01-61bc-4fe4-a306-57c536fc8d27.png">

The module exists. The symbol does not.

**Comment by kitsonk** [comment]
Is it a bug? Leo and I discussed this. I know we are using a query parameter to identify a resource, but the resource is still not found. What do you propose to show instead of a not found?

**Comment by lucacasonato** [comment]
I propose it says "Symbol not found" instead of "Module not found" :)

**Comment by kitsonk** [comment]
Doh! I thought you were complaining about getting a 404, not the error message. I can't read.
