### ISSUE TITLE
Bug: Creating module on private repo

### ISSUE THREAD

**Issue by BlackAsLight** [denoland/dotland#2439]
So I just tried publishing a module called basic_jsx. I forgot to make the github repo public though but Denoland still let me create the webhook. I went and changed the status of the repo and not the webhook is returning 400. Denoland doesn't display basic_jsx in the search results but it does say the name is taken.

I guess the bug is that Denoland shouldn't let webhooks be created on private repos or don't make the webhook break when they get switched to public.

**Comment by kitsonk** [comment]
> while it currently still doesn't show up in the search results

The updating of the search index currently happens on an hourly basis.
