### ISSUE TITLE
When you create a module on deno.land, it auto creates an unusable import name.

### ISSUE THREAD

**Issue by Codevendor** [denoland/dotland#2440]
Not sure if this is me doing something wrong or your website code is wrong or logic doesn't work correctly for auto naming import tags.

I created my first deno module on github. Then added your hooks properly and published a release. 

My module is on github is 
https://github.com/Codevendor/type_of

My deno.land version is this:
https://deno.land/x/type_of@v1.0.0

The import tag in question is found here:
https://deno.land/x/type_of@v1.0.0/mod.ts

The auto generated import tag looks like this:
import * as typeOf from "https://deno.land/x/type_of@v1.0.0/mod.ts";

My module first of all is snake case type_of as module name but it created  (* as typeOf) instead of (* as type_of), but that is really not the whole problem. the import will not work because my module is a global function.

It being global the import needs to look like:
 import {} from "https://deno.land/x/type_of@v1.0.0/mod.ts";

Because it doesnt import anything. My code creates a global method called type_of() that you can access anywhere your import without naming anything with alias.

**Comment by kitsonk** [comment]
The import statement is a best guess and may not make sense in a lot of cases.

Global modules are rare and generally considered an anti-pattern. There is no easy way to tell what the intent is and we are catering to the 99% of cases.

If the auto generated usage is not sufficient, you can add an initial JSDoc block with a `@module` tag about proper usage or you can address it in your README which is displayed on the root of the module: https://deno.land/x/type_of@v1.0.0

Also the canonical way to import a module with global side-effects the doesn't get elided is:

```ts
import "https://deno.land/x/type_of@v1.0.0/mod.ts";
```
