### ISSUE TITLE
Third Party Module is only showing the mod.ts file

### ISSUE THREAD

**Issue by cdschexnide** [denoland/dotland#2455]
I developed a 3rd party module called Redlock in June. Until recently, any time I wanted to search for it I could search for Redlock on the 3rd party module section of deno.land. However, now when I perform that same search it sends me to the mod.ts file of the project (https://deno.land/x/redlock@v1.0/mod.ts) instead of the readme. In addition, instead of showing code it gives a very high level list of functions, classes, variables, types, and interfaces. It's linked to the GitHub repository (https://github.com/oslabs-beta/Deno-Redlock) through a webhook. There had been no changes to the GitHub repo when this started occurring. Someone suggested putting all files besides readme inside of a src directory and leave the readme at the root of the project. I did that but nothing changed. I'm not quite sure how to go about returning it to it's original state.

**Comment by crowlKats** [comment]
README has been fixed a few days ago, as now there is ab info view on the root of a module (https://deno.land/x/redlock@v1.0). by default, the view for a path is a documentation-based view
