### ISSUE TITLE
CodeBlock shows scrollbars

### ISSUE THREAD

**Issue by jespertheend** [denoland/dotland#2492]
![image](https://user-images.githubusercontent.com/2737650/190857306-2e79e502-ff02-475f-b761-89d1a934371f.png)
This is both on Windows and Ubuntu, macOS is fine if you have scrollbars set to disappear in the OS settings.

**Comment by lucacasonato** [comment]
This is probably using `overflow: scroll` rather than `overflow-y: auto`.

**Comment by jespertheend** [comment]
Oops, I forgot to mention, I dug a little deeper into this.
`overflow: scroll` is applied here:
https://github.com/denoland/doc_components/blob/edc545e8d00b5fd2387aeeb029b2157c5bf10c63/doc/usage.tsx#L74
I was about to submit a PR but then I realised this might break some things and I gave up on it. 😶
I'm not sure in what other places the `Usage` component is used.

**Comment by crowlKats** [comment]
@jespertheend its only used in 2 places, its fine that change that, so PR is welcome

**Comment by jespertheend** [comment]
I've opened https://github.com/denoland/doc_components/pull/35 and I've verified that it indeed fixes the issue. Once that is merged the importmap will still need to be updated to point to the new commit.
