### ISSUE TITLE
Page https://deno.land/api@v1.25.4 is Not Found

### ISSUE THREAD

**Issue by liruifengv** [denoland/dotland#2502]
The page `https://deno.land/api@v1.25.4` is 404. But the `https://deno.land/api@latest` is working.
When i click `Go to Latest`, it is still goto 404.
Something is wrong.

![image](https://user-images.githubusercontent.com/25167721/191881149-9bc868d5-8dae-4fbf-a1f4-07e23ee317a5.png)

**Comment by crowlKats** [comment]
Thanks for reporting, this has been fixed now
