### ISSUE TITLE
`https://deno.land/manual@latest/introduction` is wrong.

### ISSUE THREAD

**Issue by liruifengv** [denoland/dotland#2503]
On the `https://deno.land/api@latest` page, toggle the `Manual` tab， go to `https://deno.land/manual@latest/introduction`, it is getting wrong. 
![image](https://user-images.githubusercontent.com/25167721/191883529-2048d4e6-0376-4d65-8b1b-f7f2a788fbd2.png)

**Comment by crowlKats** [comment]
So actually `/api@latest` shouldnt work, its more of a side-effect of some behind the scenes stuff. will give a think what could be done, however most people shouldnt even be aware of it being a valid version for the api endpoint

**Comment by liruifengv** [comment]
Maybe we can redirect to the latest version?

**Comment by crowlKats** [comment]
I am not in favour of adding this as it will not match the behaviour of the registry, and adds an additional way to do the same action as an pre-existing solution, so closing.
