### ISSUE TITLE
Module not published, Failed to run dependency analysis v2

### ISSUE THREAD

**Issue by nils-jansen** [denoland/dotland#2520]
I just published a module as described in the docs, however it is not showing up at https://deno.land/x/airbag
A version is automatically appended to the URL, so I assume the release creation must have worked, there are just no files.

This is the current status page: https://deno.land/status/633b2e93dae66ec51b7e3da9

Would be grateful for any help.

Edit: I am also already able to import the module using the deno.land URL, just the webpage isn't showing up.

**Comment by kitsonk** [comment]
I am not sure entirely what went wrong.  It wasn't an issue with registry2, it was an issue with publishing on docland.

I manually reloaded the module and it appears to be working now.
