### ISSUE TITLE
Sticky sidebar on desktop

### ISSUE THREAD

**Issue by ydcjeff** [denoland/dotland#2525]
I would like to give some UX feedback on the new design of module docs. Currently the sidebar showing module name, module source, docs, GitHub repo, versions, etc. gets scrolled along with the main content on the right. For the very long READMEs and module docs, it is very frustrating to scroll to the top to switch between source code view and docs view, to get the GitHub repo link, choose versions, etc.

It would nice if the left sidebar is sticky.

Visual preview (std README):

![Screenshot 2022-10-06 at 18 24 15](https://user-images.githubusercontent.com/32727188/194307418-724a2009-0fda-4905-bd23-ce9166f0e1f9.png)

**Comment by crowlKats** [comment]
Making it sticky wont work, as often the sidepanel will be taller than the screen (in manual, API, and various modules), so would be against this.

**Comment by crowlKats** [comment]
Closing as not really viable for aforementioned reasons
