### ISSUE TITLE
`JavaScript` code blocks don't have syntax highlighting

### ISSUE THREAD

**Issue by regseb** [denoland/dotland#2529]
Hi,

`JavaScript` (PascalCase) code blocks don't have syntax highlighting in Deno Third Party Modules.

````Markdown
```JavaScript
import Cron from "https://deno.land/x/cronnor/mod.js";
```
````

But `javascript` (lowercase) and `js` blocks do have highlighting.

Exemple with:

- `JavaScript` (PascalCase): [Deno](https://deno.land/x/cronnor@v2.0.0):x: / [GitHub](https://github.com/regseb/cronnor/tree/v2.0.0#readme):heavy_check_mark: / [npm](https://www.npmjs.com/package/cronnor/v/2.0.0):heavy_check_mark: ([source](https://github.com/regseb/cronnor/blob/v2.0.0/README.md?plain=1#L21-L32))
- `javascript` (lowercase): [Deno](https://deno.land/x/yargs@v17.6.0-deno#simple-example):heavy_check_mark: / [GitHub](https://github.com/yargs/yargs/tree/v17.6.0#simple-example):heavy_check_mark: / [npm](https://www.npmjs.com/package/yargs/v/17.6.0):heavy_check_mark: ([source](https://github.com/yargs/yargs/blob/v17.6.0/README.md?plain=1#L60-L71))
- `js`: [Deno](https://deno.land/x/lodash@4.17.19#installation):heavy_check_mark: / [GitHub](https://github.com/lodash/lodash/tree/4.17.21#installation):heavy_check_mark: / [npm](https://www.npmjs.com/package/lodash/v/4.17.21):heavy_check_mark: ([source](https://github.com/lodash/lodash/blob/4.17.21/README.md?plain=1#L44-L59))

Direct use of Prism.js (the tool used by dotland for syntax highlighting) is case insensitive: https://jsbin.com/xikurikeli/1/edit?html,output

**Comment by LeoDog896** [comment]
^ this issue was upstream! I created a PR to resolve this, then all this project would need is a dependency bump.
