### ISSUE TITLE
Unable to specify Subdirectory once module published

### ISSUE THREAD

**Issue by Tom-Hudson** [denoland/dotland#2531]
I am the author of https://deno.land/x/test_nino

I used the instructions found [here](https://deno.land/add_module) to originally setup the module and never set the optional `Subdirectory`.

Since then I have started using the [denoify npm package](https://www.npmjs.com/package/denoify) to create a deno version of my module inside the `deno_dist` directory: https://deno.land/x/test_nino@v1.1.5/deno_dist

However, I now have no way to update the config and specify the submodule.

Please can you update this for me? And maybe consider a way in the future for others that adopt usage of something like denoify to do this themselves.

**Comment by kitsonk** [comment]
@Tom-Hudson if you could please e-mail `modules@deno.com` and we can provide more direct support to be able to update information in the backend system and coordinate publishing for the module.

**Comment by ssalbdivad** [comment]
@Tom-Hudson I ran into the same issue thinking it was some sort of internal config that I'd have to email about, but missed the fact that the "Subdirectory" option actually just adds a query parameter to the request URL that can be modified directly on GitHub, as was mentioned in [this issue](https://github.com/denoland/dotland/issues/1712) which links to [this API reference](https://github.com/denoland/deno_registry2/blob/main/API.md).

@kitsonk Obviously, this was a pain to track down and it would be great if there were clearer documentation about publishing and managing modules on deno.land.

**Comment by Tom-Hudson** [comment]
@ssalbdivad thank you so much. I never did have a reply to my email and this is still a problem I have.

I was actually thinking about dropping deno support through frustration and just letting people import as an npm module.

I'll update the webhook URL and hopefully have this working for the next version. It is annoying since you can't unpublish older versions, but oh well. Feels like this should be mentioned in the denoify docs. I might do a PR if I find a good place to add it.

**Comment by ssalbdivad** [comment]
@Tom-Hudson I'm on a tight deadline and was considering whether it was worth posting, but it really brightened my day to learn it was helpful, so thanks 🥰

Tagging @lucacasonato since it looks like @kitsonk might not be working on Deno right now. I'm sure it would save some devs a lot of hassle even to just link to the [existing API doc](https://github.com/denoland/deno_registry2/blob/main/API.md) from the "Advanced Options" section of https://deno.land/add_module.
