### ISSUE TITLE
Query parameter is included in import in doc page

### ISSUE THREAD

**Issue by lucacasonato** [denoland/dotland#2533]
https://deno.land/x/tabler_icons_tsx@0.0.1/tsx/3d-rotate.tsx?s=default

<img width="1236" alt="Screenshot 2022-10-14 at 14 41 15" src="https://user-images.githubusercontent.com/7829205/195849523-4bdaac78-4a49-4ff4-8489-570b6119189b.png">

**Comment by kitsonk** [comment]
It was partially fixed (https://github.com/denoland/doc_components/pull/39) but it was actually incomplete and this should resolve it: https://github.com/denoland/doc_components/pull/43.
