### ISSUE TITLE
Search seems broken

### ISSUE THREAD

**Issue by darrachequesne** [denoland/dotland#2540]
Hi! On the https://deno.land/ website, the following resources currently return a HTTP 500 error:

- https://deno.land/_frsh/js/h8xe5cqr962g/plugin-twind-main.js
- https://deno.land/_frsh/js/h8xe5cqr962g/main.js
- https://deno.land/_frsh/js/h8xe5cqr962g/island-hellobar.js
- https://deno.land/_frsh/js/h8xe5cqr962g/island-globalsearch.js

![Screenshot from 2022-10-18 15-05-55](https://user-images.githubusercontent.com/13031701/196437879-d4719d40-a36f-4238-9dc7-b0524d6cb948.png)

Which seems to break the search functionality.

![Screenshot from 2022-10-18 15-07-55](https://user-images.githubusercontent.com/13031701/196438249-50beec80-6ef5-4b86-9286-ca8a82b80522.png)

Could it be linked to https://github.com/denoland/dotland/commit/233c97c4848ecbf6e14482288b7c1d8d2f3a507c?

OS: Ubuntu
Browser: Chrome / Firefox

**Comment by darrachequesne** [comment]
Thank you for your quick actions! :clap:

**Comment by crowlKats** [comment]
this actually hasnt been properly fixed yet, just the PR has been reverted. keeping open until proper fix lands
