### ISSUE TITLE
Select Canonical URLs for manual pages

### ISSUE THREAD

**Issue by kitsonk** [denoland/dotland#2557]
We started adding canonical URLs in the header of pages for the built-ins, std and third party and it has helped search engines find the "correct" version of something.  The Google Search Console for `deno.land` though indicates that manual of the manual pages are falling through the cracks because of the lack of a canonical.

Something like the logic for built-ins, std and third party should work for the manual.

**Comment by crowlKats** [comment]
This has been addressed.
