### ISSUE TITLE
Show examples deno.land documentation rendering

### ISSUE THREAD

**Issue by baetheus** [denoland/dotland#2566]
I maintain a Deno "library" with many entrypoints [here](https://deno.land/x/fun@v2.0.0-alpha.4). One of the things I'd like to do is document the overall usage and paradigm of each file in its heading using the jsdoc @module tag. This *sort of* works with deno.land but it seems that the module information is truncated to only the first paragraph. And example is:

* [Source rendering on deno.land](https://deno.land/x/fun@v2.0.0-alpha.4/optics.ts?source)
* [Documentation rendering on deno.land](https://deno.land/x/fun@v2.0.0-alpha.4/optics.ts)
* [Documentation rendering on doc.deno.land](https://doc.deno.land/https://raw.githubusercontent.com/baetheus/fun/main/optics.ts)

Is it possible to have deno.land/x modules render documentation more in line with doc.deno.land?

**Comment by crowlKats** [comment]
i dont see anything being truncated on either; the only difference is that deno.land/x/ currently doesnt render examples, which is something we do want to add

**Comment by baetheus** [comment]
@crowlKats That tracks. I did a quick search and couldn't find a ticket for rendering examples. If you want I can adjust the title of this ticket to cover adding examples rendering, otherwise it seems this should be closed.

**Comment by crowlKats** [comment]
Example rendering has been implemented.
