### ISSUE TITLE
Duplicate and missing listed versions on deno.land/x

### ISSUE THREAD

**Issue by janispritzkau** [denoland/dotland#2605]
This module has a bugged version list: https://deno.land/x/minecraft_lib (0.0.9 missing, and 0.0.5 duplicated twice)

![Screenshot from 2022-11-23 12-00-55](https://user-images.githubusercontent.com/1692391/204633296-1016e8db-ce3e-4ac3-a864-8407e40bb6a2.png)

After publishing version 0.0.10, 0.0.9 reappeared in the version list.

**Comment by crowlKats** [comment]
Closing in favour of #2567, as it has the same underlying issue
