### ISSUE TITLE
Module versions list scroll bar does not work

### ISSUE THREAD

**Issue by GJZwiers** [denoland/dotland#2606]
The scroll bar does not seem to show up in some modules on `deno.land/x`, this is showing on the main page on e.g. https://deno.land/x/dci@v2.6.7:
![afbeelding](https://user-images.githubusercontent.com/34610306/204886065-9f34fb9a-4bd9-4d8a-b45b-64a1723f7942.png)
Scrolling down and viewing older versions is not possible.

**Comment by crowlKats** [comment]
those are all the versions that the system knows. did you maybe only publish it on the registry after 2.6.2?

**Comment by GJZwiers** [comment]
That's probably it, I forgot I renamed this module a while ago and republished. Closing this.
