### ISSUE TITLE
The latest tag is ignored

### ISSUE THREAD

**Issue by roj1512** [denoland/dotland#2611]
https://deno.land/x/grammy/mod.ts redirects to v1.11.2 while the latest version is v1.12.0. v1.12.0 is also not listed, neither in the version list, nor in the dropdown. It is also not marked as the latest version: The "Go to latest" button does not redirect to it.

**Comment by crowlKats** [comment]
I have manually fixed this. Sorry for any inconvenience

**Comment by KnorpelSenf** [comment]
Do you know what caused this? Can it happen again?

**Comment by crowlKats** [comment]
I am not completely sure; it potentially could happen again. i will investigate this in the coming weeks.

**Comment by KnorpelSenf** [comment]
This happened again, I opened #2677.
