### ISSUE TITLE
Markdown Renderer fails to render codeblocks in lists.

### ISSUE THREAD

**Issue by LePichu** [denoland/dotland#2622]
Markdown renderer fails to render markdown properly if it detects there are codeblocks in a list.

Reference module page: https://deno.land/x/esbuild_plugin_sass_deno@v0.1.0

- `deno.land/x/`:
![deno land_x_esbuild_plugin_sass_deno@v0 1 0](https://user-images.githubusercontent.com/62379502/207314689-a80c8d0a-eddc-49ce-8d64-62f59dedefc4.png)

- GitHub:
![github com_LePichu_esbuild-plugin-sass-deno](https://user-images.githubusercontent.com/62379502/207314734-76dc163e-5b63-46a4-81af-2fa7a09e23a2.png)

**Comment by bartlomieju** [comment]
@crowlKats please take a look

**Comment by LeoDog896** [comment]
This was an older upstream issue in [marked.js](https://marked.js.org/), should be fixed in https://github.com/lucacasonato/deno-gfm/pull/26
