### ISSUE TITLE
The blog link should maybe be exposed more

### ISSUE THREAD

**Issue by sigmaSd** [denoland/dotland#2626]
Currently the blog link is hidden in the footer of the page 
![image](https://user-images.githubusercontent.com/22427111/207946471-1034aadf-7533-4d2a-81ee-5460eee3e6f2.png)

I think its an important link and should be exposed more (release announcement are there for example) 

Rust site has it at the top https://www.rust-lang.org/ 
![image](https://user-images.githubusercontent.com/22427111/207946666-1cb3d152-ce24-4807-ad5f-f8e2f87efeae.png)

 with a convenient link to the last version release notes

**Comment by bipo38** [comment]
Can I pick this  ?

**Comment by crowlKats** [comment]
We do not have any further space in the header; however we will use the announcement banners more.
Respectfully closing

**Comment by sigmaSd** [comment]
Its just a suggestion, thanks @crowlKats for looking into it,
