### ISSUE TITLE
[Suggestion] Make sidebar and navbar fixed.

### ISSUE THREAD

**Issue by yakuppgeyikk96** [denoland/dotland#2638]
Generally on the pages, how would it be that navbar and sidebar are fixed and only document can be scrolled. Thus I can navigate to other pages easily no matter where I am on the page.

**Comment by crowlKats** [comment]
Sidebar already addressed in #2525.
 Navbar is quite difficult on mobile, and if you are on the module view one would want the module navbar to be sticky as well, which is a massive amount of screenspace.
