### ISSUE TITLE
More key points of Deno presented on page

### ISSUE THREAD

**Issue by sobanieca** [denoland/dotland#2643]
Hi,

I really like the new Deno landing page, I just wonder if it would make sense to add 1 more "key point" and modiy 1 on why to choose Deno (but I don't know how to articulate it to make it 'catchy', so I will just leave it here, maybe someone will find it useful and use it to modify landing page). I'm refering to the following part of page:

![image](https://user-images.githubusercontent.com/2606245/210185460-8f711d4b-1e6a-4e38-9f66-757eba667bd1.png)

## Rich standard library

There is theory that each 5 minutes new JS framework is being created. When working with Node.js it was always frustrating for me to see lot's of libs for common tasks and I was having a headache which one to choose. With Deno's standard library I find it as a great advantage that I don't need to search for some external libraries to accomplish many common tasks.

## Next-gen serverless

Rename from _Hussle-free deployment_ to _Next-gen serverless_. I feel like it makes sense to put more accent on `serverless` keyword.

What do you think? For me those 2 points are quite important and attract me to Deno a lot :)

**Comment by bartlomieju** [comment]
@lambtron please handle this issue

**Comment by sobanieca** [comment]
Hey,

Actually I would suggest to change existing 3 points to following:

Rich standard library | All-in-one tooling | Next-gen serverless
-|-|-
No need to spend hours trying to figure out which library to choose for common tasks | Built in Typescript, linter, code formatter, ability to build a self-contained executable, test runner, IDE integration and more. | Get access to many modern serverless platforms like Deno Deploy which simplify global deployments with no server configuration

**Comment by lambtron** [comment]
Hi @sobanieca we really appreciate your time and effort in communicating what you felt was special about Deno and how you wanted that to appear on our landing page.

we're definitely gonna take your input in account for the next time we make a change to the website.

gonna close this issue, but thanks again for helping out.
