### ISSUE TITLE
How to change a third party module github repo?

### ISSUE THREAD

**Issue by wujunzhuo** [denoland/dotland#2664]
We published a third party module with name `yomo` several months ago in the repo [yomorun/cli](https://github.com/yomorun/cli). For some reason we decided to move all the code in `yomo/cli` to our main repo [yomorun/yomo](https://github.com/yomorun/yomo). But it seems that the module name `yomo` has been strictly bound to the original repo.

I found a closed issue https://github.com/denoland/dotland/issues/1631 with the same problem. However, I hope to find a way for  developers to change the ownership of a module by themselves. Has deno supported this feature?

**Comment by crowlKats** [comment]
please email modules@deno.com for resolving this kind of issue. there is no way for individuals to handle this themselves.
