### ISSUE TITLE
Version tagged latest is not the most recent version

### ISSUE THREAD

**Issue by KnorpelSenf** [denoland/dotland#2677]
If you take a look at [this package](https://deno.land/x/grammy) you'll see that you will be redirected to version 1.14.0 as the latest version. However, we actually published 1.14.1 a few hours after that. It's actually available [here](https://deno.land/x/grammy@v1.14.1) but the version is not listed.

This already happned before and was reported in #2611. I am not aware of any work being done to prevent this issue from happening in the future.

**Comment by KnorpelSenf** [comment]
@crowlKats could you fix it again manually?

I'll leave this issue open until the underlying bug is found and fixed.

**Comment by crowlKats** [comment]
ugh i hate our caching. ill take a look

**Comment by crowlKats** [comment]
This has been fixed now:
![image](https://user-images.githubusercontent.com/13135287/218225886-38f87300-2b16-4716-98ed-de171e229a65.png)
If you still see it wrong, give it a few minutes.

I sadly havent had time to look into our caching infrastructure yet.

**Comment by KnorpelSenf** [comment]
> I sadly havent had time to look into our caching infrastructure yet.

Should we maybe leave this open until then?
