### ISSUE TITLE
Link to GitHub on source code pages are sometimes broken

### ISSUE THREAD

**Issue by connorjburton** [denoland/dotland#2690]
I picked a few random pages from the third party modules list and noticed some links are broken.

The GitHub icon in the right of the `Directory` heading 404

https://deno.land/x/redis@v0.29.2?source
https://deno.land/std@0.177.0?source

These page works

https://deno.land/x/aws_api@v0.7.0?source
https://deno.land/x/eszip@v0.36.0?source

**Comment by crowlKats** [comment]
This seems to have been fixed.
