### ISSUE TITLE
Background colors not matching (with GFM?)

### ISSUE THREAD

**Issue by roj1512** [denoland/dotland#2700]
![image](https://user-images.githubusercontent.com/49933115/222517789-9443982e-e3b7-4c0a-9b37-83bf2559963d.png)

**Comment by hashrock** [comment]
My browser renders it as white 🤔 
What is your browser / os you are using?

**Comment by roj1512** [comment]
```text
Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0
```

**Comment by hashrock** [comment]
Thank you! not reproduced with osx + firefox + darkmode. still looking for way to reproduce it

**Comment by hashrock** [comment]
Close with https://github.com/denoland/dotland/pull/2708
