### ISSUE TITLE
[low priority] Code expample on docs pages incomplete

### ISSUE THREAD

**Issue by Creative-Difficulty** [denoland/dotland#2732]
On the documentation for the native logger (https://deno.land/std@0.151.0/log/README.md?source=#filehandler) and other modules in the `import`s, the `$STD_VERSION` does not seem to be filled in. I believe this is an issue with markdown styling.
In other code examples the version number for the standard library import is filled in (for example [here](https://deno.land/std@0.151.0/dotenv/mod.ts)).
Greetings, Alex

**Comment by Creative-Difficulty** [comment]
Sorry, it appears that this is intentional

**Comment by crowlKats** [comment]
No this should be gettingreplaced.

**Comment by Creative-Difficulty** [comment]
@crowlKats I have an Idea! Maybe we could set up a bot (or use an existing one) to update the markdown file once a new version of the standard library (or other libs) is released. Maybe something like [this](https://github.com/marketplace/actions/generate-update-markdown-content) or [this](https://spinscale.de/posts/2021-10-29-github-actions-updating-github-wiki-after-edit.html).

**Comment by crowlKats** [comment]
A bot isnt necessary; we already do a replace for the $STD_VERSION string when rendering, but seems that for some reason it isnt working properly

**Comment by Creative-Difficulty** [comment]
Ok understood! So should we keep this open for progress tracking or close it. Alternatively i can rename it

**Comment by crowlKats** [comment]
lets keep it open

**Comment by lino-levan** [comment]
There are no longer any READMEs in submodules. I believe this issue should be closed.

**Comment by Creative-Difficulty** [comment]
Thanks for your contribution @lino-levan, but please do your research first. The READMEs still exist!

**Comment by lino-levan** [comment]
I must be misunderstanding something, please point to an example README where this issue is present.
