### ISSUE TITLE
Add built with ... to README.md

### ISSUE THREAD

**Issue by Creative-Difficulty** [denoland/dotland#2736]
I would very much appreciate a list of the technologies used to build this website in README.md

**Comment by Thisisaarush** [comment]
Could you please add more context to the issue?
I'm unable to understand what the actual issue is.

**Comment by Creative-Difficulty** [comment]
@Thisisaarush I would love to see the technologies, with which the website was built (nextjs, sveltekit, react etc.) somewhere in the README

**Comment by crowlKats** [comment]
Since we are in the process of archiving this repo, I'll not add this, however as a reference this repo is fully written in [Fresh](https://fresh.deno.dev/)
