### ISSUE TITLE
update versions.json for 1.33.2

### ISSUE THREAD

**Issue by wydengyre** [denoland/dotland#2754]
This is preventing me from updating my CI `setup-deno` tasks to use 1.33.2.

**Comment by crowlKats** [comment]
we released a new version of `setup-deno` that uses https://deno.com/versions.json instead; it shouldnt require changing anything as it was still published under v1

**Comment by wydengyre** [comment]
@crowlKats hmm, then that file needs to be updated somehow, as it includes the `std` correspondence of `"v1.33.2":"0.186.0"`, but not `"v1.33.2"` in the preceding versions array.

**Comment by crowlKats** [comment]
You are right; seems that was missed. It is updated now
