### ISSUE TITLE
emphasize on typescript

### ISSUE THREAD

**Issue by scarf005** [denoland/dotland#2759]
![image](https://github.com/denoland/dotland/assets/54838975/29ce37bc-6939-4b31-a216-89b2e36d0f3c)
(example picture)

i think one of the core benefit for deno over node is how easy it is to run typescript out of the box. therefore, changing `javascript` to `typescript` could emphasize it more.

**Comment by crowlKats** [comment]
it however isnt a typescript runtime. There is a section further down regarding typescript support out of the box.
