### ISSUE TITLE
Community column missing in Deno.land footer 

### ISSUE THREAD

**Issue by sant123** [denoland/dotland#2764]
The community column no longer appears in footer.

https://github.com/denoland/doc_components/blob/main/footer.tsx#L45

![image](https://github.com/denoland/dotland/assets/7959437/0c0bd5bc-9bad-4b00-88c7-a7285c3b7fe3)

Please could you take a look?

Thank you!

**Comment by crowlKats** [comment]
We don't actually use this repo anymore, which explains the discrepancy. I will remove the file in doc_components, and this repo will also be archived in the next few days.

We removed the community section because we close sourced the repo for the website, making community submissions difficult.

**Comment by sant123** [comment]
Thanks @crowlKats for the response 😁
