### ISSUE TITLE
re-add dark mode

### ISSUE THREAD

**Issue by oplik0** [denoland/dotland#409]
The new design is great, but unlike the older version it lacks dark mode.

I know that this is apparently worked on, but still - adding this issue to document this and perhaps inform others of the lack/status of this feature.

**Comment by slikts** [comment]
Everything in my system is set to use dark mode, including web sites using [Dark Reader](https://darkreader.org/), but this doesn't work for deno.land, so now I have an actual headache from basically staring into a spotlight (it's late).

**Comment by wojpawlik** [comment]
Dark Reader works for me on deno.land in Static and Filter(+) mode.

**Comment by mumumilk** [comment]
I was thinking about submiting a PR for this issue, but before, i have a couple of questions:

- Do yall think it is a good idea to use tailwind's experimental dark mode feature? If so, should we do it based on `prefers-colors-scheme` only or build a toggle somewhere ?
- It is required to stick to default tailwind's gray palette?
- Should I submit a PR only when the whole docs are with dark mode or it can be a work-in-progress-style PR ?

**Comment by lucacasonato** [comment]
> I was thinking about submiting a PR for this issue, but before, i have a couple of questions:
> 
> * Do yall think it is a good idea to use tailwind's experimental dark mode feature? If so, should we do it based on `prefers-colors-scheme` only or build a toggle somewhere ?
> * It is required to stick to default tailwind's gray palette?
> * Should I submit a PR only when the whole docs are with dark mode or it can be a work-in-progress-style PR ?

Hey @mumumilk, this issue is actually way more involved than it seems because we have user provided content on the website (e.g. https://deno.land/x/oak/README.md). Before starting on this we should discuss how we want user provided content to behave (what should it look like).

I think a good start would be to use the experimental dark mode feature in Tailwind with the `prefers-color-scheme` setting, and only style a few simple pages (`/artwork`, the homepage, `/benchmarks`). We can merge that and get some user feedback before we start styling markdown content.

**Comment by sno2** [comment]
> 
> 
> > I was thinking about submiting a PR for this issue, but before, i have a couple of questions:
> > 
> > * Do yall think it is a good idea to use tailwind's experimental dark mode feature? If so, should we do it based on `prefers-colors-scheme` only or build a toggle somewhere ?
> > * It is required to stick to default tailwind's gray palette?
> > * Should I submit a PR only when the whole docs are with dark mode or it can be a work-in-progress-style PR ?
> 
> Hey @mumumilk, this issue is actually way more involved than it seems because we have user provided content on the website (e.g. https://deno.land/x/oak/README.md). Before starting on this we should discuss how we want user provided content to behave (what should it look like).
> 
> I think a good start would be to use the experimental dark mode feature in Tailwind with the `prefers-color-scheme` setting, and only style a few simple pages (`/artwork`, the homepage, `/benchmarks`). We can merge that and get some user feedback before we start styling markdown content.

Hey lucas.  Is this response still accurate?

**Comment by crowlKats** [comment]
We have discussed this internally and have come to the conclusion that this is not something we are currently interested in due to various ongoing design works and complexity & maintainability of implementing this; as such I am closing this issue.
