### ISSUE TITLE
Downloads number of package

### ISSUE THREAD

**Issue by smkamranqadri** [denoland/dotland#464]
Just curious to know which is used most but I didn't see anything on deno.land/x

**Comment by smkamranqadri** [comment]
For starters, adding number of stars might help people to choose.

**Comment by AnandChowdhary** [comment]
I don't see how this would be possible, because deno.land/x is just serving files from GitHub/etc., not from a dedicated registry like npm. Perhaps on the CDN side, number of file requests can be tracked?

**Comment by lucacasonato** [comment]
This is possible, but will probably be difficult.

**Comment by smkamranqadri** [comment]
How about adding stars badge like this.

https://img.shields.io/github/stars/oakserver/oak.svg?style=social&label=Star&maxAge=2592000

**Comment by smkamranqadri** [comment]
Something like this.

<img width="971" alt="Screenshot 2020-05-16 at 10 58 06 AM" src="https://user-images.githubusercontent.com/13115396/82112198-261a4100-9764-11ea-9674-66f5c3e73256.png">

**Comment by kidonng** [comment]
The registry is still in early stages (lacks lots of features, etc.), may be too young to add an analytics.
Showing GitHub stars is both simple and effective.

**Comment by smkamranqadri** [comment]
Sorry for being late, I got busy. I created the pull request. Feedback and suggestions are appreciated.

**Comment by smkamranqadri** [comment]
I believe we can close this issue, PR is merged for the badge and database.json is temporary so once we have solution for that then this can be done.

**Comment by kitsonk** [comment]
Closing in favour of #2358
