### ISSUE TITLE
Search on stdlib page

### ISSUE THREAD

**Issue by maman** [denoland/dotland#530]
Hi!

Please consider a search feature on the stdlib page - https://deno.land/std

deno’s stdlib are pretty big, and it includes some niceties e.g code examples. I think it’ll help people to explore and understand the stdlib by using the search feature.

**Comment by maman** [comment]
also might be related with #470?

**Comment by kidonng** [comment]
#470 is about manual search, while this issue is about stdlib search.
For the moment you can use GitHub search: https://help.github.com/en/github/searching-for-information-on-github/searching-code#search-by-file-location

**Comment by lucacasonato** [comment]
Update: You can now search through all of the file names per module - so like github file finder
