### ISSUE TITLE
Consider adding support to different languages

### ISSUE THREAD

**Issue by mechamobau** [denoland/dotland#550]
It would be nice if the Manual and the Home Page could be translated into different languages. Maybe a good library choice to use in this case is `next-i18next`.

https://github.com/isaachinman/next-i18next

**Comment by Nugine** [comment]
We have already translated the manual to Chinese (zh-CN).
Here is the repo: <https://github.com/Nugine/deno-manual-cn>.

We can provide a translated version by replacing the urls in [util/manual_utils.ts](https://github.com/denoland/deno_website2/blob/master/util/manual_utils.ts).

How about treat the translations as special versions?

**Comment by crowlKats** [comment]
We have deprecated the translations page, and supporting various translations ourselves is quite unrealistic and extremely hard to maintain, so closing
