### ISSUE TITLE
Development node process takes too much memory

### ISSUE THREAD

**Issue by buckle2000** [denoland/dotland#556]
When I run `yarn dev`, there is this one node process using all the memory (I have only 4G of RAM) and CPU all the time. I have to run it with `nice -n 10` to keep my computer usable, but then it still uses a lot of memory. It is probably related to https://github.com/zeit/next.js/issues/7929. I don't know any easy fix to this.

**Comment by lucacasonato** [comment]
I don't know how to fix this either. Maybe a recent next.js update has fixed this. This is not an issue with this repo as far as I am concerned.

**Comment by crowlKats** [comment]
We dont use node anymore, so closing
